### ISSUE TITLE
DECLARE IGNORE for DOLIST variable complains "unknown variable"

### ISSUE THREAD

**Issue by robert-dodier** [Clozure/ccl#109]
Hi, I'm working with CCL on Linux.

lx86cl --version reports:
Version 1.11.5/v1.11.5  (LinuxX8632)

uname -a reports:
Linux freekbox 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:23:46 UTC 2014 i686 i686 i686 GNU/Linux

I'm attempting to ignore the loop variable for DOLIST, but I get a warning message about an "unknown variable". I expected that there should be neither a warning about the IGNORE declaration nor a warning about the unused lexical variable.

```
? (dolist (x '(1 2 3)) (declare (ignore x)) (print 1))
;Compiler warnings :
;   In an anonymous lambda form at position 0: IGNORE declaration for unknown variable X
;   In an anonymous lambda form at position 0: Unused lexical variable X

1 
1 
1 
NIL
```

Without the ignore, I still get the warning about the unused variable. I believe that behavior is correct:

```
? (dolist (x '(1 2 3))  (print 1))
;Compiler warnings :
;   In an anonymous lambda form at position 0: Unused lexical variable X

1 
1 
1 
NIL
```

For comparison, when I try `(dolist (x '(1 2 3))  (print 1))` in SBCL, I get a warning about the unused variable, as expected, and when I try `(dolist (x '(1 2 3)) (declare (ignore x)) (print 1))` there are no warnings or errors, as expected.

**Comment by svspire** [comment]
There's a typo in #'extract-bound-decls-for-dolist-var.

**Comment by xrme** [comment]
cherry-picked to 1.11 as 0f8bedaa047f255c583b17839312ceca8965b038

**Comment by xrme** [comment]
Thanks for the bug report.
