### ISSUE TITLE
ASDF and pretty-printer problem

### ISSUE THREAD

**Issue by svspire** [Clozure/ccl#112]
The following form appears in ccl/tools/asdf.lisp:

    (format s (compatfmt "~@<Retry ASDF operation.~@:>”))

In CCL, compatfmt is a no-op so for purposes of testing this reduces to

    (format t "~@<Retry ASDF operation.~@:>")

which throws a “Missing Argument” error in CCL. This line of code is especially egregious because if ASDF encounters an error when it’s loading files and the user tries to restart in the CCL IDE, the “Missing Argument” error throws to the AltConsole and recovery is basically impossible, because the error happens in the drawing of the restarts GUI window.

Since I have no idea how the Common Lisp pretty-printer is supposed to work (and I’ve tried to read the documentation several times), I can’t tell if this is an error in ASDF or an error in CCL’s #'format implementation. I have been working around this by modifying compatfmt to get rid of the pretty-printer gobbledygook on CCL (that’s what compatfmt is for, after all), but if this is really a bug in CCL’s implementation we should probably fix it there.

**Comment by svspire** [comment]
Gail Zacharias reports (email to openmcl-dev):
CCL is wrong.  In format-logical-block, the check for non-empty *format-arguments* should only happen in the (not asign) case.

**Comment by xrme** [comment]
fix cherry-picked to 1.11 branch in 6f0ffb9
