### ISSUE TITLE
Problem building x86 version on Sierra

### ISSUE THREAD

**Issue by rpgoldman** [Clozure/ccl#117]
Trying to rebuild the development version from GitHub sources, I get this error:

```
ld  -macosx_version_min 10.6 -arch i386 -dynamic  -o ../../dx86cl -e start -pagezero_size 0x11000 -seg1addr 0x00011000 -sectalign __TEXT __text 0x1000 x86-spjump32.o x86-spentry32.o x86-subprims32.o imports.o pmcl-kernel.o gc-common.o bits.o thread_manager.o lisp-debug.o image.o memory.o x86-gc.o x86-utils.o x86-exceptions.o unix-calls.o mach-o-image.o x86-asmutils32.o mach_exc_server.o lispdcmd.o plprint.o plsym.o x86_print.o xlbt.o   -"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk"/usr/lib -lcrt1.o  -lSystem
ld: unexpected token: !tapi-tbd-v2 file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib/libSystem.tbd' for architecture i386
make: *** [Makefile:103: ../../dx86cl] Error 1
make: Leaving directory '/Users/rpg/src/ccl-1.12rc/lisp-kernel/darwinx8632'
```

TBQH, I have no idea what this error means.

**Comment by eschaton** [comment]
What version of Xcode is at Xcode.app, and do you happen to be using an `ld` from a different Xcode?

That can happen in two cases: Because `xcode-select -print-path` points at a different Xcode which a bare `ld` invocation to call, or because you have a different Xcode’s Command Line Tools package installed which a bare `ld` will use call.

**Comment by rpgoldman** [comment]
Thanks!  That looks right -- it looks like I'm accidentally using `ld` from MacPorts (`/opt/local/bin/ld`) instead of `/usr/bin/ld`.  That said, how do I fix this?  If I was using the Makefile directly, I would do
```
make LD=/usr/bin/ld
```
...but I don't know how to override my environment when it's lisp calling make.

**Comment by eschaton** [comment]
Good question; I don’t remember if we had it for Xcode 3.2, but the makefile could use `$(xcrun cc)` to invoke the compiler, `$(xcrun ld)` to invoke the linker, and so on. (That’s basically what the stubs do anyway.) There were also arguments to `xcodebuild` to have it return the path to a tool from within Xcode.

You may want to get rid of that MacPorts linker in any case, if it’s not compatible with the modern SDK.

**Comment by xrme** [comment]
Here are a couple of suggestions.

You can build the lisp kernel as a separate step.

It looks like you want the 32-bit x86 lisp for some reason.  So, in that case, you would go to `lisp-kernel/darwinx8632` and type `make clean` and then `make LD=/usr/bin/ld`.  I think the makefile is written in such a way that that should work.

Or, just take `/opt/local/bin` out of your path before running make.

After that, `cd ../..`, start the lisp (via `./dx86cl`, and `(rebuild-ccl :clean t)`.  The `:full` does the same thing as `:clean` but it also uses run-program to run make in the proper lisp kernel build directory.

Similarly, you could just take `/opt/local/bin` out of your path before starting ccl.  Then, when you did `(rebuild-ccl :full t)`, you'll get the right `ld`.

The makefile for the 64-bit lisp kernel doesn't call `ld` directly, so you probably wouldn't have the same problem with it.

**Comment by rpgoldman** [comment]
> It looks like you want the 32-bit x86 lisp for some reason. 

Actually, I **didn't** want the 32-bit lisp!  But I followed the instructions on the documentation site, and they said to do `ccl -n`, and when I look at `scripts/ccl`, I see that it selects x86.  And I didn't realize that `ccl64` was a thing. 😜😬

The good news is that I don't get that error with `ccl64`.  The bad news is that I just killed my ccl64 full rebuild job after 40 minutes, with no error messages!

Explanation:

I usually try to have both 32-bit and 64-bit installed, in order to test ASDF on CCL, but I don't typically build from source, since it's usually most important that ASDF be compatible with the release version of CCL, not the developer version -- that's your problem! 😉

But it seemed worth checking to make sure that `UIOP:RUN-PROGRAM` and `UIOP:LAUNCH-PROGRAM` are compatible with any changes to CCL's `RUN-PROGRAM`.

**Comment by xrme** [comment]
Thanks for trying to take a look.

I'm not sure what's going on you cause you to have trouble building ccl.  I do it almost every day on multiple operating systems.  I just did it on my usual machine, which is an iMac running macOS 10.13.3.

Nothing user-visible about ccl:run-program changed, so I am fairly confident that uiop:run-program is in no danger.

The change in question is very low-level: instead of building the argv[] for execve on some arbitrary thread's stack, we now (again) build it on the stack of the thread that actually calls fork.

**Comment by xrme** [comment]
I'm closing this as stale.

I'm using macOS Ventura 13.5 and Xcode tools 14.3.1, and I know that the lisp builds on that platform. I'm not really sure how far back you can successfully go with older macOS and Xcode tools.
