### ISSUE TITLE
Alt console doesn't run in newest High Sierra

### ISSUE THREAD

**Issue by martinfraserbrooks** [Clozure/ccl#118]
High Sierra 10.13.4
Clozure Common Lisp Version 1.12-dev/v1.12-dev.0-34-g6c1e5df2  (DarwinX8664)

<img width="936" alt="alt console fail" src="https://user-images.githubusercontent.com/2828622/38209375-2f50e994-3682-11e8-91c9-754e63533bbe.png">

**Comment by martinfraserbrooks** [comment]
Sorry, should have also indicated:
MacBook Pro (15 inch, 2017)
2.8 GHz i7

**Comment by xrme** [comment]
I don't remember if it has ever worked to launch the AltConsole program by double-clicking it from the Finder.

One thing you could try is to rebuild the AltConsole app.  To do this, go into `cocoa-ide/altconsole` and type `make clean`.  Also remove `AltConsole.app` if it is there.  (For some reason, `make clean` doesn't remove the application bundle.)

If you then start a command-line lisp and evaluate `(require 'cocoa-application)`, this should (as a side effect of building an IDE) rebuild the AltConsole app and it should work.

Let me know if that works for you.  If it doesn't, I'll have to do more troubleshooting.

**Comment by martinfraserbrooks** [comment]
Worked !
Thanks,
Martin
