### ISSUE TITLE
Replace all tabs with spaces

### ISSUE THREAD

**Issue by phoe** [Clozure/ccl#121]
<center><img src="https://www.emacswiki.org/pics/static/TabsSpacesBoth.png"></center>

I will be up for completing this task next week. I have no idea if any of the parts of CCL depend on the presence of tabs in code and will therefore break when I replace them with spaces, but I'll gladly check it out.

**Comment by eugeneia** [comment]
While mixed tabs and spaces is awkward, is it awkward enough to justify obfuscating the VCS history? If I do a `git-blame` and a block of code shows up as `2018: replaced tabs with spaces`, I will not be happy.

I would suggest doing this gradually for new code added and changes to existing code, but not globally all at once.

**Comment by phoe** [comment]
`git blame -w` ignores whitespace changes.

Dnia 20 kwietnia 2018 13:10:47 CEST, Max Rottenkolber <notifications@github.com> napisał(a):
>While mixed tabs and spaces is awkward, is it awkward enough to justify
>obfuscating the VCS history? If I do a `git-blame` and a block of code
>shows up as `2018: replaced tabs with spaces`, I will not be happy.
>
>I would suggest doing this gradually for new code added and changes to
>existing code, but not globally all at once.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Clozure/ccl/issues/121#issuecomment-383063988

-- Wysłane za pomocą K-9 Mail.

**Comment by phoe** [comment]
I have already talked to @xrme and will not be doing a global change in whitespace in CCL. It *does* seem counterproductive to pollute blame logs like that.

Dnia 20 kwietnia 2018 13:21:54 CEST, Max Rottenkolber <notifications@github.com> napisał(a):
>> `git blame -w` ignores whitespace changes. 
>
>While that mitigates the symptom I gave as an example, I do not think
>it answers the more general question of whether these kinds of changes
>are productive enough to deserve a change.
>
>> I think writing up a style guide and adhering to it on future
>development would be more productive than applying our current
>transient ideals to the existing codebase.
>
>Maybe that’s just me never having had an issue with the existing
>codebase formatting talking...
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Clozure/ccl/issues/121#issuecomment-383066260

-- Wysłane za pomocą K-9 Mail.
