### ISSUE TITLE
EQUALP on EQL hash tables appears to be using EQ, not EQL, to compare complex keys

### ISSUE THREAD

**Issue by pfdietz** [Clozure/ccl#134]
See attached file.  The comparison is successful (as it should be) if the hash tables are :test 
equal.
[bug5.lisp.gz](https://github.com/Clozure/ccl/files/2064948/bug5.lisp.gz)

This is on CCL 1.11.5 x86 Linux

**Comment by xrme** [comment]
From a quick glance, it appears that `need-use-eql` (and `need-use-eql-macro`) need to be revised now that there are special typecodes for complex-single-float and complex-double-float objects.

**Comment by xrme** [comment]
Fixed in c444e10120159f9b388eb087699a7c28f2c0e384

Thank you for the bug report.
