### ISSUE TITLE
ccl-tests: CCL.ISSUE\#23 failed with Vers. 1.12-dev/v1.12-dev.1 (DarwinX8664)

### ISSUE THREAD

**Issue by jdabel** [Clozure/ccl#137]
macOS Version 10.13.5
iMac 17" 2017, 4.2 GHz, i7

RUN-TESTS
? (run-tests)
Doing 21903 pending tests of 21903 tests total.
Invoking restart: #<RESTART CL-TEST::FOO #x2A33C13D>
Invoking restart: #<RESTART CL-TEST::FOO #x2A33C13D>
Invoking restart: #<RESTART CL-TEST::FOO #x2A33C13D>
Invoking restart: #<RESTART CL-TEST::FOO #x2A33C13D>
Invoking restart: #<RESTART CL-TEST::FOO #x2A33C13D>

Test CL-TEST::CCL.ISSUE\#23 failed
Form: (LET ((CL-TEST::A (MAKE-ARRAY 4 :ELEMENT-TYPE '(COMPLEX DOUBLE-FLOAT))) (CL-TEST::B (MAKE-ARRAY 4 :ELEMENT-TYPE '(COMPLEX DOUBLE-FLOAT)))) (DOTIMES (CL-TEST::I 4) (SETF (AREF CL-TEST::B CL-TEST::I) (COMPLEX (* 1.0D0 CL-TEST::I) (* 2.0D0 CL-TEST::I)))) (REPLACE CL-TEST::A CL-TEST::B) (EQUALP CL-TEST::A CL-TEST::B))
Expected value: T
Actual value: NIL.

================ Test suite failed ================

1 out of 21903 total tests failed: 
   CL-TEST::CCL.ISSUE\#23.
(FUNCALL DO-TESTS :COMPILE COMPILE :VERBOSE VERBOSE :CATCH-ERRORS T)
took 81,963,706 microseconds (81.963710 seconds) to run.
      1,494,289 microseconds ( 1.494289 seconds, 1.82%) of which was spent in GC.
During that period, and with 8 available CPU cores,
     77,317,015 microseconds (77.317020 seconds) were spent in user mode
      4,273,741 microseconds ( 4.273741 seconds) were spent in system mode
 8,119,204,032 bytes of memory allocated.
 52,885 minor page faults, 2,418 major page faults, 0 swaps.
(CL-TEST::CCL.ISSUE\#23)
?

**Comment by xrme** [comment]
This test passes on the current version 1.12.2.
