### ISSUE TITLE
HyperSpec lookup broken in IDE

### ISSUE THREAD

**Issue by xrme** [Clozure/ccl#147]
If HyperSpec lookup is enabled, trying to look up a symbol will result in an error that saying that Data/Map_Sym.txt couldn't be loaded.

The IDE uses a pretty naive way of loading that file (via NSData's dataWithContentsOfURL:options:error: method), and that appears to be failing.

**Comment by svspire** [comment]
I can't reproduce this on 1.12-dev. What version are you using?

**Comment by xrme** [comment]
This happened to be 1.12-dev on a Mojave beta.

**Comment by xrme** [comment]
I just remembered App Transport Security.  See https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW35

The upshot is that macOS 10.11 and later require the use of https.  In 05d6af0426b2 I configured ATS to allow plain http.

**Comment by xrme** [comment]
It appears that, as a rule, Apple doesn't like Mac App Store software to disable the requirement for https.  They do hold open the possibility that one can justify the need for this during app review.

**Comment by xrme** [comment]
I don't think it applies for `file://` URLs.
