### ISSUE TITLE
Error loading slime.

### ISSUE THREAD

**Issue by vinay** [Clozure/ccl#168]
I get the following error using slime to load ccl.

(progn (load "/Users/Vinay/Projects/slime/swank-loader.lisp" :verbose t) (funcall (read-from-string "swank-loader:init")) (funcall (read-from-string "swank:start-server") "/var/folders/nd/pp7vkxdd02sbx9v2bhjyxhmw0000gn/T/slime.17703"))

Clozure Common Lisp Version 1.11.5  (DarwinX8664)

For more information about CCL, please see http://ccl.clozure.com.

CCL is free software.  It is distributed under the terms of the Apache
Licence, Version 2.0.
? ;Loading #P"/Users/Vinay/Projects/slime/swank-loader.lisp"...
;; 
;; Error loading /Users/vinay/.slime/fasl/2.22/clozure-version_1.11.5__(darwinx8664)-darwin-x86-64/packages.dx64fsl:
;;   Not a FASL file.
;; 
> Error: Not a FASL file.
> While executing: CCL::%LOAD, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
1 >

**Comment by vinay** [comment]
Yep, just tried that. Also, tried brew reinstall clozure-cl. Get the same error.

**Comment by xrme** [comment]
Closing as stale.

For what it's worth, I'm able to use recent SLIME with CCL 1.13 on my Intel-based Macintosh.
