### ISSUE TITLE
improper insistence on fixnum type

### ISSUE THREAD

**Issue by xrme** [Clozure/ccl#171]
From #ccl on freenode:

```
(defun bug ()
  (let ((indentation 0))	
    (macrolet ((with-indent (inc &body body)
		 `(prog2 (incf indentation ,inc)
		      (progn ,@body)
		    (decf indentation ,inc))))
      (labels ((foo () (1+ indentation)))
	(with-indent 2.5 "")))))
```

Expected result is "".  Actual result is an error: "The value 2.5 is not of the expected type FIXNUM".

The labels form seems to be implicated somehow.

**Comment by informatimago** [comment]
I don't reproduce it on "Version 1.12-dev (v1.12-dev.3-27-g7a42fe0c) Darwinx8664"
either with compile-file or load, evaluating the defun in the slime repl, or evaluating (bug) in the three cases.

**Comment by kpoeck** [comment]
Still happening to me on macosx, latest everything

**Comment by xrme** [comment]
Gilbert Baumann wrote on openmcl-devel:

I looked into before-mentioned issue on github. The smallest test case
exposing this bug that I could find is like the following:
```
(DEFUN BUG ()
  (DECLARE (OPTIMIZE (SPEED 1) (SAFETY 3) (DEBUG 1) (COMPILATION-SPEED 0)))
  (LET ((X 0))
    (LABELS ((FOO () (1+ X)))
      (SETQ X PI)
      (1+ X))))
```
I get
```
(bug)
=> #<BOGUS object @ #x302001E0E255>
```
Which is bad. It goes away with (COMPILATION-SPEED 3). Remove the
LABELS and the bug disappears.

I nailed that down to the following change:
<https://github.com/Clozure/ccl/commit/bed5cf811ae157298903036276c079e336ae1cf9>
```
   diff --git a/compiler/nx0.lisp b/compiler/nx0.lisp
   index 110c6c41..15101941 100644
   --- a/compiler/nx0.lisp
   +++ b/compiler/nx0.lisp
   @@ -1599,7 +1599,7 @@ Or something. Right? ~s ~s" var varbits))
               (with-program-error-handler (lambda (c) (runtime-program-error-form c))
                 (parse-body (%cddr lambda-form) *nx-lexical-environment* t))
              (setf (afunc-acode p) (nx1-lambda (%cadr lambda-form) body decls)))))
   -
   +    (rewrite-acode-form (afunc-acode p))
        (nx1-transitively-punt-bindings *nx-punted-vars*)
        (setf (afunc-blocks p) *nx-blocks*)
        (setf (afunc-tags p) *nx-tags*)
```
I suggest until we find the real issue with REWRITE-ACODE-FORM, we
disable it, if we can.

**Comment by xrme** [comment]
A more targeted change would seem to be edit acode-rewrite.lisp and change the definition of `acode-rewrite-labels-flet` so that it doesn't do any rewriting there.

In other words, do the inverse of
```
+
 (def-acode-rewrite acode-rewrite-labels-flet (labels flet)  asserted-type (vars funcs body p2decls)
-  (declare (ignore vars funcs))
+  (declare (ignore vars))
+  (dolist (func funcs)
+    (let* ((*nx-current-function* func))
+      (rewrite-acode-form (afunc-acode func))))
   (with-acode-declarations p2decls (rewrite-acode-form body asserted-type)))
```

(which was changed in 3117330ad50003ec2c5923bcb62d84ef4f55acd6)

**Comment by svspire** [comment]
Source of the problem is this line:
  `(LET ((X 0))`
if this is changed to
  `(LET ((X 0.0d0))`
then everything works fine.

The optimizer is looking at what it thinks the type of X is, which is a fixnum because of that 0, and then compiling a fixnum add/2 instruction, which when handed 1 and PI, creates a bogus object. It's not recognizing that it guessed wrong about the type of X.

When you set `(COMPILATION-SPEED 3)`, this optimization is not done, so everything works.

The bug is somewhere in `def-acode-rewrite acode-rewrite-add2`.

**Comment by xrme** [comment]
We call (possibly unintentionally?) `rewrite-acode-form` in both `compile-named-function` and in `nx1-compile-lambda`.

In principle, it seems that doing it twice shouldn't hurt, semantically speaking. But, as pointed out in the comment above, removing the call from `nx1-compile-lambda` avoids the bug reported here.

Maybe that call was added so that `nx1-compile-inner-function` would go through the acode rewriting?

**Comment by xrme** [comment]
```
(let ((*nx-current-code-note* nil))
  (nx1-compile-lambda 'bug-no-labels '(lambda ()
                                 (let ((x 0))
                                   (setq x pi)
                                   (1+ x)))))
(pprint (decomp-acode (afunc-acode *))) =>
(LAMBDA-LIST NIL
 (LET* ((X 0))
   (PROGN (PROGN (SETQ-LEXICAL X (IMMEDIATE 3.141592653589793D0)))
          (ADD2 1 (LEXICAL-REFERENCE X)))))
```

```
(let ((*nx-current-code-note* nil))
  (nx1-compile-lambda 'bug-with-labels '(lambda ()
                                 (let ((x 0))
                                   (labels ((foo () (1+ x)))
                                     (setq x pi)
                                     (1+ x))))))
(pprint (decomp-acode (afunc-acode *))) =>
(LAMBDA-LIST NIL
 (LET* ((X 0))
   (LABELS ((#:FOO #<AFUNC #x30200181776D>))
     (PROGN (PROGN (SETQ-LEXICAL X (IMMEDIATE 3.141592653589793D0)))
            (FIXNUM-ADD-NO-OVERFLOW 1 (LEXICAL-REFERENCE X))))))
```
In the above snippet, we have somehow erroneously decided that we know that `x` is a fixnum.
```
(let ((*nx-current-code-note* nil))
  (nx1-compile-lambda 'bug-with-labels-setq '(lambda ()
                                 (let ((x 0))
                                   (labels ((foo () (setq x (1+ x))))
                                     (setq x pi)
                                     (1+ x))))))
(pprint (decomp-acode (afunc-acode *))) =>
(LAMBDA-LIST NIL
 (LET* ((X 0))
   (LABELS ((#:FOO #<AFUNC #x3020017C733D>))
     (PROGN (PROGN (SETQ-LEXICAL X (IMMEDIATE 3.141592653589793D0)))
            (ADD2 1 (LEXICAL-REFERENCE X))))))
```
But, if we setq x in the labels form, we don't conclude that `x` is a fixnum after all.

**Comment by xrme** [comment]
https://github.com/Clozure/ccl/blob/2278015201c66d16f4735daf12364fdb6ed2a7d3/compiler/nx0.lisp#L525-L531

In the code above, we don't actually check to see if the var was setq'd. If we do that, and return `nil` if so, then that fixes (or masks) the bug reported here.

I can't tell if `acode-var-type` is doing the right thing, though:
https://github.com/Clozure/ccl/blob/2278015201c66d16f4735daf12364fdb6ed2a7d3/compiler/nx2.lisp#L517-L527

In the case of our friend the function`bug` defined above, it seems that it can happen that the `var-type` slot of the `#<VAR X ...>` object can get set before we notice that `x` is later setq'd. Maybe we want to treat `var-type` as provisional, or unconditionally check `$vbitsetq` every time?

**Comment by xrme** [comment]
I think changing the `infer-lexical-reference` function is acceptable. This makes it match the comment, in any case.

**Comment by xrme** [comment]
Still broken:
```
(defun bad ()
  (let ((x 0))
    (labels ((foo () (1+ x)))
      (print (foo))
      (setq x pi)
      (print (foo))
      (1+ x))))
```
This gives:
```
? (bad)
1 
#<BOGUS object @ #x3000000F4CB5> 
4.141592653589793D0
```
So it looks like we still think we know that `x` is a fixnum in the internal function `foo`.
