### ISSUE TITLE
lisp kernel doesn't build on FreeBSD 12.0-RC3

### ISSUE THREAD

**Issue by xrme** [Clozure/ccl#173]
Building the lisp kernel fails.

After fixing the obvious error (by adding `#include <x86/trap.h>` to `platform-freebsd8664.h`, we get the error
```
/usr/bin/ld: error: x86-subprims64.o: SHF_MERGE section size must be a multiple of sh_entsize
```

**Comment by msvoelker** [comment]
By changing the linker to the GNU linker, I was able to build lisp-kernel in FreeBSD 12.0 Release. However, when I executed the built fx86cl64 file, I got a segmentation fault.

My solution (on FreeBSD 12.0 Release) was to use the ccl 1.12 snapshot (March 2018) release (see https://github.com/Clozure/ccl/releases/tag/v1.12-dev.3).
