### ISSUE TITLE
100% CPU usage with ccl 1.12-dev.4/slime/emacs/mojave

### ISSUE THREAD

**Issue by informatimago** [Clozure/ccl#174]
To reproduce:

M-x slime in emacsformacosx.com emacs.app (the "standard" GNU emacs application distribution for macOS).

This will eventually consume near 100% of CPU time in emacs and ccl, and turn on the ventilators!

I'll report more precise info tomorrow, now the processes are killed for the nigh.

**Comment by xrme** [comment]
closing as stale
