### ISSUE TITLE
方向键乱码Direction key garbled

### ISSUE THREAD

**Issue by luzhiguang** [Clozure/ccl#178]
苹果电脑在终端里使用ccl时方向键乱码
Apple computer garbled when using ccl in the terminal

**Comment by binghe** [comment]
Are you talking about `^[[A^[[B^[[C^[[D` when you hit the keys "up", "down", "left", "right"?

**Comment by zhlisp** [comment]
是的，是按上下左右的方向键时乱码。

**Comment by binghe** [comment]
This is *not* a bug, instead it's normal behavior when a terminal program is taking standard input without linking GNU readline. The same thing you can see in CMUCL, SBCL, Allegro CL, LispWorks and many other interactive programs.  Either use an IDE or things like `rlwrap` as @macdavid313 suggested above.
