### ISSUE TITLE
自带示例和苹果商店IDEBring your own example and Apple Store IDE

### ISSUE THREAD

**Issue by luzhiguang** [Clozure/ccl#179]
自带示例演示学习无法通过，比如那个汇率转换器，发布成包后无法正确运行，部分示例在最新的系统下无法运行。
苹果商店IDE已经是四年前的了，在新系统下已无法正常使用了。
The built-in example demo can't pass, for example, the exchange rate converter, which can't run correctly after being released into a package, some examples can't run under the latest system.
The Apple Store IDE is four years old and is no longer working under the new system.

**Comment by binghe** [comment]
You can get a working CCL app from http://setf.clozure.com/~rme/ccl.pkg

**Comment by xrme** [comment]
The Mac App Store version of CCL is broken, and is no longer available in the store.

Please use `(require 'cocoa-application)` to build an IDE locally.
