### ISSUE TITLE
(REBUILD-CCL :FULL T): Not a symbol address: #x3020001008E3

### ISSUE THREAD

**Issue by phoe** [Clozure/ccl#185]
While attempting to fix #111 I have run into what seems to be an error in CCL compiler and/or FASL loader.

Steps to reproduce:

1) Clone my forked CCL source code from https://github.com/phoe-trash/ccl
2) Put 1.12-dev.1 bootstrapping binaries in the directory `(lisp-implementation-version) ;=> "Version 1.12-dev/v1.12-dev.1  (LinuxX8664)"`
3) Run `(rebuild-ccl :full t)` to bring CCL up to date with master
4) Evaluate code from https://plaster.tymoon.eu/view/1140#1140 to bootstrap package-local nicknames inside the active Lisp image
5) Run `(rebuild-ccl :full t)`
6) CCL catches fire:

```common-lisp
> Error:  Not a symbol address: #x3020001008E3
> While executing: (SETF XLOAD-SYMBOL-PLIST), in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
1 > :B
 (7FCF27E8D198) : 0 ((SETF XLOAD-SYMBOL-PLIST) 52913998137619 52913998137571) 181
 (7FCF27E8D1B8) : 1 (FUNCALL #'#<$FASL-DEFUN> #<FASLSTATE #x7FCF27C7226D>) 293
 (7FCF27E8D1E8) : 2 (%FASLOAD "/home/phoe/Projects/Git/ccl/level-0/nfasload.lx64fsl" #(#<Compiled-function $FASL-NOOP (Non-Global)  #x30000011950F> #<Compiled-function $FASL-S32-VECTOR (Non-Global)  #x3020009E880F> #<Compiled-function $FASL-CODE-VECTOR (Non-Global)  #x3020009E78FF> #<Compiled-function $FASL-CLFUN (Non-Global)  #x3020009E241F> #<Compiled-function $FASL-LFUNCALL (Non-Global)  #x3020009F13EF> ...)) 1325
 (7FCF27E8D280) : 3 (XLOAD-FASLOAD (#P"/home/phoe/Projects/Git/ccl/level-0/X86/X8664/x8664-bignum.lx64fsl" #P"/home/phoe/Projects/Git/ccl/level-0/X86/x86-array.lx64fsl" #P"/home/phoe/Projects/Git/ccl/level-0/X86/x86-clos.lx64fsl" #P"/home/phoe/Projects/Git/ccl/level-0/X86/x86-def.lx64fsl" #P"/home/phoe/Projects/Git/ccl/level-0/X86/x86-float.lx64fsl" ...)) 909
...
```

Full compilation log and backtrace available at https://plaster.tymoon.eu/view/1138#1138

**Comment by phoe** [comment]
This issue is related to me trying to define a `SETF` function in level-0 via `(defun (setf ...) ...)` - level 0 does not seem to be capable of that.

Moving the `SETF` function definitions into level 1 has fixed this issue.

**Comment by xrme** [comment]
Yes, what you can do in level-0 is often limited.  As the files in level-1 get loaded, the system becomes more and more capable, until finally it is Common Lisp.
