### ISSUE TITLE
Performance regressions since 1.11.5 on ACL2

### ISSUE THREAD

**Issue by phoe** [Clozure/ccl#191]
While implementing #111, I have noticed that the current master performs *slower* than CCL 1.11.5 on ACL2 certify-books.

The results on my machine with -j4:

```
CCL 1.11.5:
real	193m55,838s
user	679m1,862s
sys	8m42,055s

CCL v1.12-dev.4-4-gd9740256
real    217m48,620s
user    766m15,539s
sys     8m44,711s
```

This means that book certification is taking 24 minutes longer on current master than it is on the last stable release.

**Comment by xrme** [comment]
That is a very serious performance regression. :-(

**Comment by phoe** [comment]
I think that the first step would be attempting to locate the changes that have introduced this slowdown. The naïve solution would be doing a manual search across the commits, something more contrived could be done via `git bisect`, and an even more effective solution would require someone who knows what happened in particular commits.

**Comment by phoe** [comment]
The apparent regression was a matter of improper testing - me and Matt have ruled it out in #111.
