### ISSUE TITLE
doubled characters in find-all text boxes, mojave

### ISSUE THREAD

**Issue by arthurcater** [Clozure/ccl#194]
I upgraded Mac Mini to mojave 10.14.3, 
got Lisp Version 1.12-dev (v1.12-dev.4-4-gd9740256) DarwinX8664, 
made full rebuild. 

Using cmd-shift-F for find-all, every character in the search string (flip) and in the file spec (*.lisp) gets repeated. (fflliipp)(**..lliisspp)

**Comment by arthurcater** [comment]
Sort-of oops. The plot thickens. Sorry this is long, it has an a) b) c) d) and e) part.
Starting with     ./dx86cl64 --no-init and then
;--------------------------------------------
(a) saying (require :COCOA)   then opening a lisp file, and pressing cmd-shift-f, I see a pizza wheel and in terminal
<snip a lot>
;Loading #P"ccl:cocoa-ide;fasls;search-files.dx64fsl.newest"...
;Loading #P"ccl:cocoa-ide;fasls;start.dx64fsl.newest"...
;Loading #P"ccl:cocoa-ide;fasls;xinspector.dx64fsl.newest"...
:COCOA
("IDE-BUNDLE" "OBJC-PACKAGE" "SEQUENCE-UTILS" "NAME-TRANSLATION" "OBJC-CLOS" "OBJC-RUNTIME" "BRIDGE" "OBJC-SUPPORT" "COMPILE-HEMLOCK" "HEMLOCK" "BUILDER-UTILITIES" "BUILD-APPLICATION" "COCOA")
? 2019-02-14 14:38:47.145 dx86cl64[7314:474009] Failed to connect (searchCommentsCheckbox) outlet from (SearchFilesWindowController) to (NSButton): missing setter or instance variable

> Error: Undefined function GUI::@CLASS called with arguments ("GrepResultsDataSource") .
> While executing: GUI::|-[SearchFilesWindowController awakeFromNib]|, in process Initial(0).


;;;
;;; #<APPKIT-PROCESS Initial(0) [Reset] #x3020000B940D> requires access to Shared Terminal Input
;;; Type (:y 0) to yield control to this thread.
;;;
(:y 0)


;;;
;;; Shared Terminal Input is now owned by #<APPKIT-PROCESS Initial(0) [Reset] #x3020000B940D>
;;;


;; ----------------------------------------------
(b) doing the same but requiring both :COCOA and :COCOA-APPLICATION just fails, giving 
;Loading #P"ccl:cocoa-ide;fasls;search-files.dx64fsl.newest"...
;Loading #P"ccl:cocoa-ide;fasls;start.dx64fsl.newest"...
;Loading #P"ccl:cocoa-ide;fasls;xinspector.dx64fsl.newest"...
:COCOA
("IDE-BUNDLE" "OBJC-PACKAGE" "SEQUENCE-UTILS" "NAME-TRANSLATION" "OBJC-CLOS" "OBJC-RUNTIME" "BRIDGE" "OBJC-SUPPORT" "COMPILE-HEMLOCK" "HEMLOCK" "BUILDER-UTILITIES" "BUILD-APPLICATION" "COCOA")
? (require :cocoa-application)
;Loading #P"ccl:mac-ui;fasls;cf-utils.dx64fsl.newest"...
;Loading #P"ccl:mac-ui;fasls;libdispatch.dx64fsl.newest"...
;Loading #P"ccl:mac-ui;fasls;ccl-application.dx64fsl.newest"...
;Loading #P"ccl:mac-ui;fasls;event-process.dx64fsl.newest"...
;Loading #P"ccl:mac-ui;fasls;cg.dx64fsl.newest"...
;Loading #P"ccl:cocoa-ide;fasls;constants.dx64fsl.newest"...
;Loading #P"ccl:cocoa-ide;fasls;ide-application.dx64fsl.newest"...
> Error: class_addIvar failed
> While executing: #<STANDARD-METHOD (SETF CLASS-DIRECT-SLOTS) :BEFORE (T OBJC:OBJC-CLASS)>, in process listener(1).
> Type cmd-. to abort, cmd-\ for a list of available restarts.
> Type :? for other options.
1 > 



; ----------------------------------------------
c) double-clicking on the 'temp bundle64' file created by requiring cocoa throws up a dialog saying
You can’t open the application “temp bundle64” because it is not supported on this type of Mac.


;-----------------------------------------------
d) Strangely, I think but cannot prove that the results of trying (b) and (c) were different the first time from what they are now.


;-----------------------------------------------
e) The problem I originally reported - character doubling - occurred using an image built from a complex load process. I was trying to track down another problem by searching its source files ... 

Regards to all, Arthur

**Comment by xrme** [comment]
It doesn't work to double-click `temp bundle64.app`.  If you want a double-clickable app, you can build one with `(require 'cocoa-application)` instead of using `(require 'cocoa)`.

Your report of command-shift-F failing is clearly a bug.

**Comment by xrme** [comment]
Please `git pull` and rebuild, and this problem should then be corrected.
