### ISSUE TITLE
CCL unhandled exception

### ISSUE THREAD

**Issue by aggKartik** [Clozure/ccl#195]
I am trying to use CCL for a school project that requires me to use CCL as the common lisp distribution. In Windows 10, Windows Subsystem for Linux (WSL) allows for Linux binaries to be run on a console interface. I am trying to understand this stack trace that I get when I try to run CCL. Other versions of common lisp such as SBCL which were installed using apt are working on this setup. I've tried using precompiled binaries, and building my own, both result in the same error. I'm running the following version of Linux on WSL: Ubuntu 18.04.1. I'd greatly appreciate your help understanding how I can rectify this issue

![debug](https://user-images.githubusercontent.com/24238951/53751943-72d56d00-3e7b-11e9-9ce1-360791d1c742.JPG)

**Comment by xrme** [comment]
It's possible that the Linux port of CCL just doesn't work on WSL.

Is it an option for you to use the native Windows version of CCL?

**Comment by aggKartik** [comment]
> It's possible that the Linux port of CCL just doesn't work on WSL.
> 
> Is it an option for you to use the native Windows version of CCL?

Unfortunately, I don't think so as I need to link this with an application that is using this binary specifically. I haven't tried aliasing it with a windows binary but since the other application is relying on this binary, I don't think it'll help if I change it to that.

**Comment by xrme** [comment]
In that case, I am afraid you may have to resort to using a virtual machine to run Linux.
