### ISSUE TITLE
Cannot launch or compile cocoa app

### ISSUE THREAD

**Issue by louisabraham** [Clozure/ccl#198]
Hi,

I downloaded and extracted the latest release.
I went into the `ccl/`folder and set `CCL_DEFAULT_DIRECTORY`.
I then launched both `./scripts/ccl` and `./scripts/ccl64` which worked fine.

However, when I try `(require "COCOA-APPLICATION")` or `(require "COCOA")`, I get the error
`sigreturn returned`. I also got the same error when I tried to recompile the master branch with `(ccl:rebuild-ccl :full t)`.

In fact, I get the same error as #146

**Comment by xrme** [comment]
Until we make a new release, please use the latest release snapshot.

Currently, that is https://github.com/Clozure/ccl/releases/tag/v1.12-dev.4

**Comment by eschaton** [comment]
This is #146.
