### ISSUE TITLE
Can't launch CCL from Apple App Store

### ISSUE THREAD

**Issue by j3pic** [Clozure/ccl#199]
![image](https://user-images.githubusercontent.com/26551894/55663432-b56bcb80-57d2-11e9-9078-83dc75306423.png)
I had the same problem when I tried to download from https://github.com/Clozure/ccl/releases/download/v1.11.5/ccl-1.11.5-darwinx86.tar.gz, except the error didn't happen until I tried to load quicklisp.lisp.

MacOS Mojave (10.14.1).

**Comment by eschaton** [comment]
This is #146.
