### ISSUE TITLE
{standard input}:544: Error: unknown mnemonic `define_cl_ivecot' -- `define_cl_ivecot(complex_double_float_vector,14) '

### ISSUE THREAD

**Issue by luzhiguang** [Clozure/ccl#200]
/ccl-master/lisp-kernel/linuxarm64# make
m4 -DLINUX -DARM64 -I../ ../pad.s | as   -o pad.o
m4 -DLINUX -DARM64 -I../ ../arm64-spentry.s | as   -o arm64-spentry.o
{standard input}: Assembler messages:
{standard input}:544: Error: unknown mnemonic `define_cl_ivecot' -- `define_cl_ivecot(complex_double_float_vector,14) '
../arm64-spentry.s:620: Error: immediate out of range at operand 3 -- `orr x0,x0,#tag_catch_frame'
../arm64-spentry.s:626: Error: immediate out of range at operand 3 -- `orr x0,x0,#tag_catch_frame'
../arm64-spentry.s:773: Error: immediate out of range at operand 3 -- `orr x0,x0,#tag_catch_frame'
......................
../arm64-spentry.s:3322: Error: undefined symbol TCR_STATE_FOREIGN used as an immediate value
../arm64-spentry.s:3600: Error: undefined symbol node_bias used as an immediate value
Makefile:49: recipe for target 'arm64-spentry.o' failed
make: *** [arm64-spentry.o] Error 1

**Comment by xrme** [comment]
Something is clearly broken there, but an ARM64 version CCL isn't expected to work now. Please ignore any ARM64 stuff in the sources.
