### ISSUE TITLE
Master build broken on optimizers.lisp

### ISSUE THREAD

**Issue by phoe** [Clozure/ccl#204]
It seems that the recent commits have broken building `optimizers.lisp` - compilation hangs on building that file on linux/amd64.

**Comment by phoe** [comment]
OK, I needed a different bootstrapping path. I have built master successfully using this path: 1.12-dev-dec2017 -> f120efb* -> 2912b11 -> a2fc47e (master)

*evaluate the code from https://plaster.tymoon.eu/view/1144/raw?password in order to bootstrap package-local nicknames

**Comment by fade** [comment]
fyi, ccl checked out to the tagged v1.12 is failing in this way... perhaps a patch with a new tag?

**Comment by phoe** [comment]
@fade How are you trying to build CCL? Which bootstrapping binaries do you have?
