### ISSUE TITLE
select-item-from-list bug fix

### ISSUE THREAD

**Issue by Devon7** [Clozure/ccl#206]
Here is a bug fix for SELECT-ITEM-FROM-LIST
so it will no longer fail horribly,
leaving the user stranded
in an unusable debugger
with a broken readtable.
[ccl-select-item-from-list.patch.TXT](https://github.com/Clozure/ccl/files/3100292/ccl-select-item-from-list.patch.TXT)

**Comment by xrme** [comment]
Thank you for the report and patch.  I used `with-standard-io-syntax` rather than just binding `*readtable*`.
