### ISSUE TITLE
rebuild-ccl failure: 'The value 0 is not of the expected type STRUCTURE'

### ISSUE THREAD

**Issue by acoglio** [Clozure/ccl#211]
This is on macOS Mojave. I cloned the repo, downloaded and unpacked the v1.12-dev.5 snapshot as described in https://github.com/Clozure/ccl/releases, started `./dx86cl64`, and attempted to rebuild, but I got the following error:
```
Clozure Common Lisp Version 1.12-dev (v1.12-dev.5) DarwinX8664

For more information about CCL, please see http://ccl.clozure.com.

CCL is free software.  It is distributed under the terms of the Apache
Licence, Version 2.0.
? (rebuild-ccl :full t)
Rebuilding Clozure Common Lisp using Version 1.12-dev (v1.12-dev.5) DarwinX8664
;Compiling "/usr/local/ccl/lib/systems.lisp"...
;Loading #P"/usr/local/ccl/bin/systems.dx64fsl"...
;Compiling "/usr/local/ccl/lib/compile-ccl.lisp"...
;Loading #P"/usr/local/ccl/bin/compile-ccl.dx64fsl"...
;Compiling "/usr/local/ccl/compiler/nxenv.lisp"...
;Loading #P"/usr/local/ccl/bin/nxenv.dx64fsl"...
;Compiling "/usr/local/ccl/compiler/nx.lisp"...
; Including "/usr/local/ccl/compiler/nx-basic.lisp"...
; Including "/usr/local/ccl/compiler/lambda-list.lisp"...
; Including "/usr/local/ccl/compiler/nx0.lisp"...
; Including "/usr/local/ccl/compiler/nx1.lisp"...
;Loading #P"/usr/local/ccl/l1-fasls/nx.dx64fsl"...
;Compiling "/usr/local/ccl/compiler/optimizers.lisp"...
> Error: The value 0 is not of the expected type STRUCTURE.
> While executing: X862-BIND-VAR, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
1 > 
```

**Comment by xrme** [comment]
I tried to duplicate this myself on my laptop running Mojave (still 10.14.3), and it is working for me.

Is there possibly something in your init file?  If so, please try starting up with the -n flag, e.g., `./dx86cl64 -n`.

**Comment by acoglio** [comment]
@xrme Thanks for your quick reply. I tried `./dx86cl64 -n` but I get the same result.

I do have a `~/ccl-init.lisp` file, with the following contents (specific to the ACL2 theorem prover):
```
(when (find-package "ACL2")
  ;; Suppress as much as possible at startup except for the LD info.
  (set (intern "*PRINT-STARTUP-BANNER*" "ACL2")
       nil)
  ;; Suppress the LD info.
  (eval (list (intern "SET-LD-VERBOSE" "ACL2")
              nil
              (intern "*THE-LIVE-STATE*" "ACL2"))))
```

**Comment by xrme** [comment]
OK.  If you go to your CCL directory, what does `git describe` print, please?  I just want to make sure that you're compiling the correct sources with the correct bootstrapping binaries.

**Comment by acoglio** [comment]
Certainly, it's important to double-check everything here. It prints `v1.12-dev.5-3-gb5233ade`.

**Comment by xrme** [comment]
That seems fine.  Are there any local modifications to your sources at all (as seen by `git status`)?  I sent mail a while ago talking about needing to change optimizers.lisp in order to bootstrap, but that's no longer necessary.

I don't see why it would matter, but you could also try rebuilding the lisp kernel manually (`cd lisp-kernel/darwinx8664; make clean; make`).  After that, go back to the top of the ccl directory, do `./dx86cl64 -n` and then `(rebuild-ccl :clean t)`.

Also, what's your exact macOS version, please?

**Comment by acoglio** [comment]
OS and HW info:

![Screen Shot 2019-05-06 at 12 54 56 PM](https://user-images.githubusercontent.com/2409151/57251249-3b5f7a00-6ffe-11e9-93f5-2606ea1da4f9.png)

`git status` shows no modifications -- in fact, I cloned afresh.

The `make` command worked fine, but I got a similar error with `rebuild-ccl`:

```
? (rebuild-ccl :clean t)
Rebuilding Clozure Common Lisp using Version 1.12-dev (v1.12-dev.5) DarwinX8664
;Compiling "/usr/local/ccl/lib/systems.lisp"...
;Loading #P"/usr/local/ccl/bin/systems.dx64fsl"...
;Compiling "/usr/local/ccl/lib/compile-ccl.lisp"...
;Loading #P"/usr/local/ccl/bin/compile-ccl.dx64fsl"...
;Compiling "/usr/local/ccl/compiler/nxenv.lisp"...
;Loading #P"/usr/local/ccl/bin/nxenv.dx64fsl"...
;Compiling "/usr/local/ccl/compiler/nx.lisp"...
; Including "/usr/local/ccl/compiler/nx-basic.lisp"...
; Including "/usr/local/ccl/compiler/lambda-list.lisp"...
; Including "/usr/local/ccl/compiler/nx0.lisp"...
; Including "/usr/local/ccl/compiler/nx1.lisp"...
;Loading #P"/usr/local/ccl/l1-fasls/nx.dx64fsl"...
;Compiling "/usr/local/ccl/compiler/optimizers.lisp"...
> Error: The value 0 is not of the expected type STRUCTURE.
> While executing: X862-BIND-VAR, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
1 > 
```

**Comment by xrme** [comment]
I just tried it on a similar MacBook Pro running 10.14.4, and it works for me.

Maybe make a throwaway new account any try it from there?  I'm puzzled.

**Comment by xrme** [comment]
It feels to me like you must be using some mismatched set of binaries and sources.

On my system:
```
clio:ccl rme$ openssl sha256 darwinx86.tar.gz 
SHA256(darwinx86.tar.gz)= c716ba5db9c85a8ef389be7975fe71832a9ed5cd2971ab1ad6f8bc5c9a2231e1
```
Does your archive of binaries match that?

**Comment by acoglio** [comment]
Yes, same SHA-256.

I'll try with a new account, as you suggested, later today.

**Comment by acoglio** [comment]
I tried on a newly created account and it works there. Very puzzling indeed.

**Comment by phoe** [comment]
@acoglio Are you able to reproduce the issue now using the most recent bootstrapping binaries and source from git master?

**Comment by acoglio** [comment]
@phoe Yes, same results as before. I cloned the repo afresh and downloaded the 1.2-dev.5 snapshot (which seems to be the same as when I tried back in early May).

**Comment by acoglio** [comment]
This Issue might be related to Issue #260, but as noted there the error is different and it happens on a different computer with a different macOS version.

**Comment by xrme** [comment]
A strong possibility is that `CCL_DEFAULT_DIRECTORY` is set in your environment, and is pointing to sources that are not expected.

(I think it'd be good to print out the truename of the "ccl:" logical host when we run rebuild-ccl.)
