### ISSUE TITLE
Exporting %GET-ERRNO

### ISSUE THREAD

**Issue by galdor** [Clozure/ccl#215]
Accessing `errno` when using foreign libraries is tricky because it may be a macro. SBCL offers `SB-ALIEN:GET-ERRNO`. CCL has `CCL::%GET-ERRNO`.

Would it be possible to export it ? Or to have `CCL:GET-ERRNO` that just returns `CCL::%GET-ERRNO` ? I'd be happy to write a patch (or at least to try) if CCL maintainers agree it is a good idea :)

**Comment by xrme** [comment]
`ccl::%get-errno` returns a negated value of errno.  (I don't know why.) I guess that people will find this a bit strange.

But it seems clear that users need a way to do this.

**Comment by phoe** [comment]
In that case the exported function `get-errno` should return `(- (%get-errno))` it seems.

**Comment by galdor** [comment]
PR updated.

**Comment by galdor** [comment]
It was merged, thank you!
