### ISSUE TITLE
请添加对arm64位平台的二进制发布包

### ISSUE THREAD

**Issue by luzhiguang** [Clozure/ccl#218]
现在arm的新平台开始基于64位的系统了，但ccl还没有对应的程序包，请添加下，或者讲下怎么自己用源码编译。
我用源码编译内核时代码报很多错误，我的平台是英伟达Jetson Nano，系统是ubuntu arm64位。
我想尝试用ccl来做些深度学习练习。
平台硬件信息如下

![image](https://user-images.githubusercontent.com/38294709/61499919-85e87400-a9fb-11e9-9e56-361d65bc3588.png)

感谢！

**Comment by binghe** [comment]
A brief translation: he wants CCL for ARM64 platforms (NVIDIA Jetson Nano), with potential applications on Deep Learning.

**Comment by xrme** [comment]
duplicates #11
