### ISSUE TITLE
Can't build CCL on PPC64 without heap image

### ISSUE THREAD

**Issue by BHa2R00** [Clozure/ccl#219]
System:  gentoo linux-4.19.44 on ibm power6 p520
![img1](http://t441.bha2r.xyz/20190725010534.png)

**Comment by xrme** [comment]
The last release that supported PowerPC was version 1.10.

See https://ccl.clozure.com/download-1.10.html for instructions on how to get it. I don't know if it will still run on on your machine, but it should be easy enough to try out.

The current GitHub sources can't be used to build a PowerPC version of CCL.  Resurrecting the PowerPC port would take some work (and time, and access to hardware, etc.)
