### ISSUE TITLE
1b8a369 causes trouble on raspberry pi 3

### ISSUE THREAD

**Issue by xrme** [Clozure/ccl#22]
(copied from http://trac.clozure.com/ccl/ticket/1380)

1b8a36955b919deb27b9d0e0caae86712711b7d2 causes trouble on my Raspberry Pi 3.

It reliably fails when doing (rebuild-ccl :clean t) with the following strange error.

```
;Compiling "/home/rme/ccl/compiler/nxenv.lisp"...
> Error: The value -1069547520 is not of the expected type INTEGER.
> While executing: ARM::ENCODE-ARM-IMMEDIATE, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
1 > b
*(76B87E28) : 0 (ENCODE-ARM-IMMEDIATE ???) 40
*(76B87E28) : 1 (FUNCALL #'#<ARM2-FIXNUM> #<VINSN-LIST #x1457779E> #<LREG 8 GPR {5}/LISP> 2 -267386880) 580
 (76B87E28) : 2 (ARM2-FORM #<VINSN-LIST #x1457779E> #<LREG 8 GPR {5}/LISP> 2 #<ACODE fixnum (-267386880)>) 788
 (76B87E38) : 3 (FUNCALL #'#<ARM2-IF> #<VINSN-LIST #x1457779E> #<LREG 8 GPR {5}/LISP> 2 #<ACODE call (#<# # #> # NIL)> #<ACODE fixnum (-267386880)> #<ACODE fixnum (-268435456)>) 2100
```

Linux kupo 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux

**Comment by enikesha** [comment]
Reverting this commit (after 7d86b9f) fixes build on RPi3. I've also checked https://trac.clozure.com/ccl/ticket/1257 after revert and it's problem is still there.

**Comment by xrme** [comment]
The commit ace23b99173c340cc179f7e729d696e9ea3566ec reverts 1b8a369.

Back to the drawing board.
