### ISSUE TITLE
Bootstrapping issue: Build CCL without CCL

### ISSUE THREAD

**Issue by Ambrevar** [Clozure/ccl#222]
I'm working on the [Guix](https://guix.gnu.org) package for CCL. Guix has a strong stance towards bootstrappability, in the sense that every package must be buildable from source and not depend on a binary, or, in the case of CCL, itself.

The [documentation](https://ccl.clozure.com/docs/ccl.html#create-a-bootstrapping-image) mentions that a running CCL is required to build the bootstrap image.  Is this true?  Can't it be built with, say, CLisp?

If not, how was CCL every built at its inception?
Is there any way to work around this?

**Comment by billstclair** [comment]
As far as I know, there is no way to build CCL without an existing running CCL image. It was bootstrapped back in 1986 or so as Macintosh Common Lisp, by Gary Byers, I believe, who is no longer on the planet to tell us the story. It SHOULD be possible to port the CCL compiler to portable Common Lisp, so that ANY lisp could build it, as is the case for SBCL, but I know of no attempt to do so.

**Comment by billstclair** [comment]
Note that Guix is not being entirely honest. They are depending on a GCC binary, or compatible C compiler, for ALL of their packages.

**Comment by Ambrevar** [comment]
Oh, that's too bad :(

It would be very nice to see a bootstrapping effort realized soon.
The current state of affair means that CCL is exposed to compiler
backdoors (a.k.a. Thompson attack):
https://en.wikipedia.org/wiki/Backdoor_(computing)#Compiler_backdoors

Also it somehow reduces the "free" part in "free software".

> Note that Guix is not being entirely honest. They are depending on a GCC binary, or compatible C compiler, for ALL of their packages.

For the time being, but there is active work being done to reduce the
bootstrap set to [stage0](https://github.com/oriansj/stage0), a
human-readable assembly file.
Also see the [GNU Mes](https://www.gnu.org/software/mes/) compiler
effort.

When this gets merged into Guix (could happen relatively soon), it would
mean that the whole graph of software is effectively fully compilable
from source.  Exciting times ahead!

Also I don't think Guix is being dishonest ;) This is explicitly
explained in the manual:

http://guix.gnu.org/manual/en/html_node/Bootstrapping.html#Bootstrapping

**Comment by phoe** [comment]
CCL consists of two parts: a Lisp kernel (buildable from C and assembly) and a Lisp core (buildable from Lisp). The tricky part is that the code that generates the Lisp core (compiler et al) is highly non-portable and depends on a lot of CCL internals.

The first step I'd suggest would be trying to refactor CCL internals into a set of modules that can then be independently compiled and loaded. It's pretty much impossible to boot the important parts outside CCL if the `CCL` package contains the compiler, internal functions that power the `CL` package, CCL-specific utility functions, extensions to ANSI CL, and the kitchen sink.

**Comment by xrme** [comment]
It would be cool if this was possible, but it would involve a lot of work.

Maybe one day.
