### ISSUE TITLE
List truncated to one element after calling (sort)

### ISSUE THREAD

**Issue by yoeljacobsen** [Clozure/ccl#223]
Consider the following program (which mimics an issue I found in my code - I didn't try other patterns):

```
(defclass foo ()
  ((bar :initarg :foo-bar :accessor :foo-bar)))

(defun test-sort (n c)
  (let ((test-list (loop for i from 1 to n
                         collect (make-instance 'foo :foo-bar i))))
    (dotimes (i c)
      (let* ((before (length test-list))
             (sorted (sort test-list #'> :key #':foo-bar))
             (after (length test-list)))
        (if (neq after before) 
             (error (format nil "After ~a rounds, before: ~a, after: ~a" i before after)))))
    (format t "No problem after ~a rounds~%" c)))
```

It seems sort truncates the list to 1  - try `(test-sort 2 1000)`. On my system (CCL 1.11.5 / OS X), I get: `After 0 rounds, before: 2, after: 1`

If I change the function in sort to #'<, I see no problem.

**Comment by olopierpa** [comment]
Il giorno 14 settembre 2019, alle ore 22:11, yoeljacobsen <notifications@github.com> ha scritto:

>Consider the following program (which mimics an issue I found in my code - I didn't try other patterns):

SORT is destructive function. After applying SORT to a list the original list content is undefined.

In your example, SORTED is the sorted list you want. After the call of SORT, TEST-LIST contains garbage.

>If I change the function in sort to #'<, I see no problem.

Just a random result.

**Comment by yoeljacobsen** [comment]
That is correct. Closing.
