### ISSUE TITLE
Release 1.12

### ISSUE THREAD

**Issue by phoe** [Clozure/ccl#232]
What are the blockers preventing us from releasing CCL 1.12? What needs to be done to complete CCL's release process and requirements, if any?

**Comment by phoe** [comment]
Found a list at - https://github.com/Clozure/ccl/projects/3

**Comment by xrme** [comment]
What I would like to do is to roll back some experimental compiler back-end changes that were intended to reduce stack traffic (by improving register allocation).

The idea was to get better power efficiency and better performance, but there were in fact performance regressions for ACL2 (an important workload).

**Comment by phoe** [comment]
OK - could you make an issue for that and add it to the GitHub milestone for tracking?
