### ISSUE TITLE
Crashes of CCL 1.11.7 under Mojave 10.14.6

### ISSUE THREAD

**Issue by marcoferraris** [Clozure/ccl#238]
System: macOS 10.14.6 Mojave

Launching CCL 1.11.7 crashes with the following message in AltConsole

Unhandled exception 11 at 0x7fff645d2649, context->regs at #x7ffeefbfde00
Exception occurred while executing foreign code
 at objc_release + 25
received signal 11; faulting address: 0x60000301a000
? for help
[1891] Clozure CL kernel debugger: 

If launching CCL 1.11.7 succeeds, then it crashes while quitting with the following message in AltConsole

Unhandled exception 10 at 0x7fff645d069d, context->regs at #x7ffeefbfc1a0
Exception occurred while executing foreign code
 at objc_msgSend + 29
received signal 10; faulting address: 0x7fff00000018
? for help
[1881] Clozure CL kernel debugger: 

The program apparently works under macOS Catalina

**Comment by xrme** [comment]
Thanks.  I'm investigating.

**Comment by marcoferraris** [comment]
Hi Mattew,

	may be you are interested in these comments.

I have two iMac (24 inches, mid 2007) with OS X El Capitan (version 10.11.6) and Xcode version 8.2.1. 

I was able to successfully compile CCL 1.12-dev.5, CCL 1.11.6 and CCL 1.11.7 on these machines. These compiled 'Clozure CL64' apps seem to run without problems under OS X El Capitan (10.11.6) and macOS Mojave (10.14.6) but I’m not quite sure of what happens with macOS Catalina (10.15.1) because I updated my external Catalina ssd only this afternooon. 

The app "Clozure CL (1.11.7)" downloaded from the "App Store” crashes both on El Capitan and Mojave, but works on Catalina. The old app "Clozure CL (1.11.6)" downloaded from the "App Store” was OK.

The compilation by means of Xcode 11.2 fails both under Mojave and Catalina.

Best regards
Marco Ferraris

**Comment by BobKanefsky** [comment]
I'm getting a very similar crash in 1.11.7 on startup on High Sierra.  Will upgrading to a newer macOS help?  Or downgrading CCL to the previous version, which worked?
```
Unhandled exception 10 at 0x7fff502f6e9d, context->regs at #x7ffeefbfdc30
Exception occurred while executing foreign code
 at objc_msgSend + 29
received signal 10; faulting address: 0x7fff00000018
```
macOS 10.13.6
iMac (27-inch, Late 2013)

**Comment by xrme** [comment]
The app store version runs on Catalina.  It crashes on earlier releases.

I'm not totally sure why.  I'm starting to suspect some Objective-C runtime difference.  I built the current app store release on Catalina.  If I build the exact same sources on Mojave, the resultant binary works on Mojave, but crashes on Catalina.  The thing is, in both cases, things get far enough along that the trouble arises during the process of creating a new listener (seemingly when adding its modeline).

The previous version of CCL will still run on High Sierra. I'm not sure there's a way to go back to an older app store release, is there?

**Comment by eschaton** [comment]
When you build the kernel, do you build it with `-mmacosx-version-min=10.14` or earlier in the compiler and linker invocations? That’s needed to ensure APIs newer than 10.14 are weak-linked and code & linked-binary generation are appropriate for 10.14. (We call this the “Deployment Target” in Xcode.)

**Comment by xrme** [comment]
Please go to https://github.com/Clozure/ccl/releases/tag/v1.11.8 to download a binary package that will run on Mojave (and High Sierra at least).  You can use this instead of the Mac App Store version.

**Comment by xrme** [comment]
consolidating this in #272
