### ISSUE TITLE
Crash on startup on macOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by OoglesMcGoogles** [Clozure/ccl#239]
It opens the AltConsole and says:

Error: Objective-C runtime exception:
-[EchoAreaView lock]: unrecognized selector sent to instance 0x6000001444c0
While executing: #<Anonymous Function #x300000E9F35F>, in process Initial(0).

I'm running it on a late 2011 13-inch MacBook Pro and started experiencing the crash after the last update (1.11.7).

**Comment by xrme** [comment]
Thank you for the report.  I'm investigating.

**Comment by xrme** [comment]
The Mac App Store version of CCL only runs on Catalina (and per #265, it sounds like it only runs on a specific Catalina point release).

In your case, you can download a non-App Store binary from https://github.com/Clozure/ccl/releases/tag/v1.11.8, and this will run on High Sierra (and Mojave).

If it doesn't work for you, please re-open this issue.
