### ISSUE TITLE
Terminal REPL: exit after one EOF

### ISSUE THREAD

**Issue by phoe** [Clozure/ccl#243]
https://github.com/Clozure/ccl/blob/275105afd94706d95ac955178316074931822c42/level-1/l1-readloop-lds.lisp#L298

Should we set this variable to 0 or remove it altogether along with the checks elsewhere in the code for greater cohesion with other Common Lisp implementations? I remember that the fact that CCL requires three consecutive EOFs to quit surprised me when I first tried it.

**Comment by xrme** [comment]
I remember there was some situation where there was system built in CCL, and while the authors didn't want EOF to cause the lisp to quit, they would run the lisp in some batch-type fashion where it would sometimes get wedged.  I think the "exit after some number of repeated EOF" hack was added to avoid this.

You can use `(setq ccl:*quit-on-eof* t)` to make the lisp quit on (a single) EOF. This would be something for your init file.

When `*quit-on-eof*` is `nil`, you can use C-d to exit from a break loop, which can be a nice shortcut.
