### ISSUE TITLE
Not running on macOS 10.15.2.

### ISSUE THREAD

**Issue by MartinBuchmann** [Clozure/ccl#265]
Since the update to macOS 10.15.2. I get the following error when I start the CCL Application:

```
> Error: #<A Foreign Pointer #x11FE60> has no slot named GUI::PEER.
> While executing: #<CCL::STANDARD-KERNEL-METHOD SLOT-MISSING (T T T T)>, in process Initial(0).
```

Is there anything I can do about it?

**Comment by xrme** [comment]
Is this is with the current Mac App Store version of CCL?  The current version should work on Catalina, but maybe the 10.15.2 update broke it.  That would be surprising and unfortunate.

**Comment by MartinBuchmann** [comment]
Yes, it‘s the App Store version and it seems to me that the update broke it.

**Comment by xrme** [comment]
Well, that's pretty bad news.  As a workaround, you can build the IDE from source and use it on your local system (until the next point release of the OS possibly breaks it again).

**Comment by rpgoldman** [comment]
The App Store version works for me on 10.15.2.  Not sure why.

**Comment by stoney** [comment]
The app store version is failing for me about 1/2 the time I launch it on
10.15.2 on my iMac Pro or on my PowerBook. Same Gui::Peer error.

 - Stoney
————
Stonewall Ballard    stoney@sb.org   http://stoney.sb.org

**Comment by mark-watson** [comment]
I agree with xrme, best to build from source.

**Comment by mark-watson** [comment]
Did you get a working IDE? This works fine for me on macOS 10.15.3:

March 30, 2020: building CCL IDE from source:

- get ccl source from GitHub
- make sure ccl command line tools is installed using brew (brew install ccl)
- cd ccl, run ccl on command line, then (require "COCOA-APPLICATION")
- app is in: open "/usr/local/Cellar/clozure-cl/1.11.6/libexec/Clozure CL64.app"

**Comment by MartinBuchmann** [comment]
I still see the error with the app store version and will migrate to the source built. Thanks for your help!
