### ISSUE TITLE
Upload new Windows binaries

### ISSUE THREAD

**Issue by phoe** [Clozure/ccl#266]
#233 was merged, but the new Windows binaries containing the hanging fix are not yet uploaded.

**Comment by TruePikachu** [comment]
I'm also waiting on this, especially since I don't presently have the capability to compile CCL on my own.

**Comment by snunez1** [comment]
I've just compiled a new kernel, but the hanging fix isn't in the 1.11 branch, at least as of 1.11.8. I'll upload binaries if someone is able to back-port the fix to 1.11 series.

**Comment by phoe** [comment]
> I'll upload binaries if someone is able to back-port the fix to 1.11 series.

You can likely backport it yourself - cherry-pick https://github.com/Clozure/ccl/commit/71cc1a5a59bff33dd577a8b9c3761f7e0f179848 on top of 1.11.

**Comment by snunez1** [comment]
Done, and it works. Now, how can I get the binaries uploaded? And, which one: wx86-boot64.image (bootstrapping image) or wx86cl64.image?

**Comment by phoe** [comment]
I don't know if @xrme will want to accept binaries coming from a third party. It's possible that he might want to cherry-pick that commit himself and upload a new CCL stable version with that.

**Comment by snunez1** [comment]
NP. He knows where to reach me if he wants it.

**Comment by xrme** [comment]
The 1.12.2 release has up-to-date Windows binaries.

Please weigh in on #288 if you still need/want this to go into the 1.11 branch.
