### ISSUE TITLE
Error opening files

### ISSUE THREAD

**Issue by MartinBuchmann** [Clozure/ccl#268]
I tried to understand writing binary data etc. to streams and files better and read ccl's [documentation](https://ccl.clozure.com/manual/chapter10.2.html#Extending-READ-SEQUENCE-and-WRITE-SEQUENCE) but if I try the example given there 

```
(let* ((a (make-array 3 
                               :element-type '(unsigned-byte 16)
                               :initial-contents '(26725 27756 28449))))
           (with-open-file (s "junk"
                              :element-type 'character
                              :direction :io
                              :if-does-not-exist :create
                              :if-exists :supersede)
             ;; Write six octets (three elements).
             (stream-write-ivector s a 0 6)
             ;; Rewind, then read a line
             (file-position s 0)
             (read-line s)))
``` 

I get the following error:

```
Attempt to create "junk" failed unexpectedly
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [RETRY-OPEN] Retry opening "junk"
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT-BREAK] Reset this thread
 3: [ABORT] Kill this thread

Backtrace:
  0: (CCL::MAKE-FILE-STREAM "junk" :IO CHARACTER :SUPERSEDE :CREATE FILE-STREAM :DEFAULT :PRIVATE T)
  1: (OPEN "junk" :DIRECTION :IO :ELEMENT-TYPE CHARACTER :IF-EXISTS :SUPERSEDE :IF-DOES-NOT-EXIST :CREATE :EXTERNAL-FORMAT :DEFAULT :CLASS FILE-STREAM :SHARING :PRIVATE :BASIC T)
  2: (#<Anonymous Function #x3020011ED90F>)
  3: (CCL::CHEAP-EVAL (LET* ((A (MAKE-ARRAY 3 :ELEMENT-TYPE '# :INITIAL-CONTENTS ...))) ..))
```

which I don't really understand. An empty file is created in the current working directory. I am using `"Version 1.11.6  DarwinX8664"` on macOS 10.15.2. and gave ccl full disc access so it should be able to create a file and write to it.

**Comment by phoe** [comment]
Cannot reproduce on Linux64 - it looks like a Mac-specific issue.

**Comment by MartinBuchmann** [comment]
Hmm, can anyone running macOS 10.15.2 reproduce this? I am not aware of anything special with my system but it seems that something is weird about my configuration. 

I have installed ccl using homebrew.

**Comment by metayan** [comment]
The Cocoa application listener's default working directory is "/", so trying to create a file there fails.
Plain command-line `ccl` uses the current working directory, so success depends on whether the current user has writing permissions there.
```
(current-directory)
```
or, not CCL-specifically:
```
(directory "./")
```
Tested with CCL v1.12-dev.5-17-g58d4d91c on macOS 10.3.6

**Comment by MartinBuchmann** [comment]
I'm using `ccl64` as installed by homebrew from within Emacs using SLIME and am pretty sure I have write permission in my home directory.

```
CL-USER> (current-directory)
#P"/Users/martin/"
```

**Comment by metayan** [comment]
Alright. I might be able to test on a newer macOS in a couple of days.

**Comment by xrme** [comment]
Works for me with the 1.12.2 release on macOS Ventura 13.5.
