### ISSUE TITLE
Apple Store Clozure doesn't start under OSX 10.15.1

### ISSUE THREAD

**Issue by markklein** [Clozure/ccl#276]
![Screen Shot 2020-01-08 at 1 54 20 PM](https://user-images.githubusercontent.com/8991514/72008547-14f37d80-3222-11ea-864d-9eab53b3df24.png)

**Comment by clarino** [comment]
On Catalina 10.15.3, startup of Clozure 1.11.7 is very unreliable. Sometimes it starts and runs fine. Most of the time it gets into the following error right away.
```
> Error: #<A Foreign Pointer #x409060> has no slot named GUI::PEER.
> While executing: #<CCL::STANDARD-KERNEL-METHOD SLOT-MISSING (T T T T)>, in process Initial(0).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
1 > 
```
Recovery is possible with :Q in that case.

**Comment by pfitzner** [comment]
I have nothing to add, other than to report the same error as **clarino**. On my last successful startup, I got a Listener, could create a file, but when I cancelled the Save, this:

Unhandled exception 4 at 0x7fff6f0f548e, context->regs at #x7ffeefbfe310
Exception occurred while executing foreign code
 at _os_unfair_lock_corruption_abort + 23
? for help
[18273] Clozure CL kernel debugger:

**Comment by xrme** [comment]
Sadly, the Mac App Store version of CCL is broken and no longer available.
