### ISSUE TITLE
CCL 1.11.8 won't pass Apple malware check

### ISSUE THREAD

**Issue by Blaz75** [Clozure/ccl#279]
Running macOS Catalina 10.15.3

Obtained ccl-mac-ide-1.11.8.zip from this site. The file was unzipped, installed and moved into the Applications folder without error. Opening the app triggered the following macOS display:

<img width="418" alt="Screen Shot 2020-02-19 at 3 13 04 PM" src="https://user-images.githubusercontent.com/61250298/74872123-99114880-532a-11ea-9651-5a0eea0bc4b0.png">

Clicking on System Preferences / Security & Privacy / Open Anyway triggered the following macOS display:

<img width="472" alt="Screen Shot 2020-02-19 at 3 17 36 PM" src="https://user-images.githubusercontent.com/61250298/74872508-4edc9700-532b-11ea-9002-379a9999d0d8.png">

Did not attempt to try "Open" on this display due to malware concerns.

**Comment by unya** [comment]
This is not a malware check - it's because the application is not signed and under quarantine (Everything you download from network instead of App Store is put under quarantine).

You can remove quarantine with `sudo xattr -r -d com.apple.quarantine path/to/CCL.app`

**Comment by Blaz75** [comment]
Hello Paweł,

Thanks for your help with the CCL problem. Some time after my post on Github, I decided to trust CCL as being safe from malware. The Mac operating system let me override the check and open the CCL app without having to use Mac Terminal commands. Unfortunately, CCL exhibits the same or similar problem as the version available in the App Store: CCL basically crashes on startup and Alt Console appears with various diagnostics. Other people have reported this behavior on Github. 

I think I’m stuck until Closure updates the App Store version.

Regards,

John Blasdale
john.blasdale@verizon.net

**Comment by unya** [comment]
@Blaz75 Unfortunately it's a current problem with 10.15, I somehow didn't notice that you mentioned you run 10.15 otherwise I might have highlighted the issues with it as well..

**Comment by xrme** [comment]
Downloading the latest release and building the IDE with `(require 'cocoa-application)` is the way to go.

The Mac App Store version of CCL is no longer available (currently, it seems that an IDE will run only on the OS version it is compiled on).
