### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ghost** [Clozure/ccl#282]
Not sure if its an issue, but clarification regarding installation process.

I am trying to install clozure-cl in MacOS Catalina 10.15. 
downloaded the latest release 1.11.8 and using that directory as ccl gives me this error
`dx86cl64: cannot execute: No such file or directory`

I do see that directory in release 1.11.5 but not in releases after that. So my basic understanding sort of says that I have to download 1.11.5 first and then compile for the recent releases. Is that right? or am i missing something?

Trying to install 1.11.5 version and following the procedure in docs. And on ccI64 from terminal I get the following error
`sigreturn returned`
`? for help`
`[25599] Clozure CL kernel debugger:`

And when to trying build the binary for the 1.11.8 version I keep getting this error

> make 
gm4 -DDARWIN -DX86 -DX8664 -DTCR_IN_GPR -I../ ../x86-spjump64.s | as -arch x86_64 -g -Q -o x86-spjump64.o
../x86-spjump64.s:unknown:rs_org invalid, dot past value by -17616 bytes
gm4 -DDARWIN -DX86 -DX8664 -DTCR_IN_GPR -I../ ../x86-spentry64.s | as -arch x86_64 -g -Q -o x86-spentry64.o
../x86-spentry64.s:55:4294967283 shortened to 243
../x86-spentry64.s:60:4294967291 shortened to 251
../x86-spentry64.s:77:4294967283 shortened to 243
../x86-spentry64.s:78:4294967291 shortened to 251
../x86-spentry64.s:115:4294967283 shortened to 243
../x86-spentry64.s:116:4294967291 shortened to 251
../x86-spentry64.s:117:4294967299 shortened to 3
../x86-spentry64.s:120:4294967283 shortened to 243
../x86-spentry64.s:121:4294967291 shortened to 251
../x86-spentry64.s:122:4294967299 shortened to 3
../x86-spentry64.s:157:4294967283 shortened to 243
../x86-spentry64.s:158:4294967291 shortened to 251
../x86-spentry64.s:159:4294967299 shortened to 3
../x86-spentry64.s:162:4294967283 shortened to 243
../x86-spentry64.s:165:4294967283 shortened to 243
../x86-spentry64.s:166:4294967291 shortened to 251
../x86-spentry64.s:167:4294967299 shortened to 3
../x86-spentry64.s:178:4294967283 shortened to 243
../x86-spentry64.s:183:4294967283 shortened to 243
../x86-spentry64.s:479:4294967291 shortened to 251
../x86-spentry64.s:484:4294967291 shortened to 251
../x86-spentry64.s:487:4294967291 shortened to 251
../x86-spentry64.s:490:4294967291 shortened to 251
../x86-spentry64.s:492:4294967283 shortened to 243
../x86-spentry64.s:493:4294967291 shortened to 251
../x86-spentry64.s:498:4294967283 shortened to 243
../x86-spentry64.s:502:4294967291 shortened to 251
../x86-spentry64.s:504:4294967283 shortened to 243
../x86-spentry64.s:505:4294967291 shortened to 251
../x86-spentry64.s:508:4294967291 shortened to 251
../x86-spentry64.s:512:4294967291 shortened to 251
../x86-spentry64.s:517:4294967291 shortened to 251
../x86-spentry64.s:523:4294967291 shortened to 251
../x86-spentry64.s:529:4294967291 shortened to 251
../x86-spentry64.s:537:4294967291 shortened to 251
../x86-spentry64.s:543:4294967291 shortened to 251
../x86-spentry64.s:549:4294967291 shortened to 251
../x86-spentry64.s:556:4294967291 shortened to 251
../x86-spentry64.s:563:4294967291 shortened to 251
../x86-spentry64.s:569:4294967291 shortened to 251
../x86-spentry64.s:574:4294967291 shortened to 251
../x86-spentry64.s:594:4294967283 shortened to 243
../x86-spentry64.s:614:4294967283 shortened to 243
../x86-spentry64.s:633:4294967283 shortened to 243
../x86-spentry64.s:638:4294967283 shortened to 243
../x86-spentry64.s:929:4294967291 shortened to 251
../x86-spentry64.s:943:4294967283 shortened to 243
../x86-spentry64.s:946:4294967283 shortened to 243
../x86-spentry64.s:951:4294967291 shortened to 251
../x86-spentry64.s:955:4294967291 shortened to 251
../x86-spentry64.s:956:4294967299 shortened to 3
../x86-spentry64.s:958:4294967291 shortened to 251
../x86-spentry64.s:965:4294967291 shortened to 251
../x86-spentry64.s:976:4294967283 shortened to 243
../x86-spentry64.s:979:4294967283 shortened to 243
../x86-spentry64.s:981:4294967291 shortened to 251
../x86-spentry64.s:983:4294967291 shortened to 251
../x86-spentry64.s:995:4294967283 shortened to 243
../x86-spentry64.s:998:4294967291 shortened to 251
../x86-spentry64.s:999:4294967291 shortened to 251
../x86-spentry64.s:1002:4294967283 shortened to 243
../x86-spentry64.s:1009:4294967283 shortened to 243
../x86-spentry64.s:1012:4294967291 shortened to 251
../x86-spentry64.s:1013:4294967291 shortened to 251
../x86-spentry64.s:1026:4294967291 shortened to 251
../x86-spentry64.s:1035:4294967291 shortened to 251
../x86-spentry64.s:1044:4294967291 shortened to 251
../x86-spentry64.s:1053:4294967291 shortened to 251
../x86-spentry64.s:1056:4294967291 shortened to 251
../x86-spentry64.s:1064:4294967291 shortened to 251
../x86-spentry64.s:1077:4294967291 shortened to 251
../x86-spentry64.s:1086:4294967291 shortened to 251
../x86-spentry64.s:1095:4294967291 shortened to 251
../x86-spentry64.s:1108:4294967291 shortened to 251
../x86-spentry64.s:1116:4294967291 shortened to 251
../x86-spentry64.s:1184:suffix or operands invalid for `movq'
../x86-spentry64.s:1184:4294967291 shortened to 251
../x86-spentry64.s:1190:suffix or operands invalid for `movq'
../x86-spentry64.s:1190:4294967291 shortened to 251
../x86-spentry64.s:1205:suffix or operands invalid for `movq'
../x86-spentry64.s:1205:4294967291 shortened to 251
../x86-spentry64.s:1211:suffix or operands invalid for `movq'
../x86-spentry64.s:1211:4294967291 shortened to 251
../x86-spentry64.s:1221:4294967291 shortened to 251
../x86-spentry64.s:1346:4294967291 shortened to 251
../x86-spentry64.s:1495:4294967291 shortened to 251
../x86-spentry64.s:1699:4294967293 shortened to 253
../x86-spentry64.s:1712:4294967293 shortened to 253
../x86-spentry64.s:1731:4294967293 shortened to 253
../x86-spentry64.s:1752:4294967293 shortened to 253
../x86-spentry64.s:1772:4294967291 shortened to 251
../x86-spentry64.s:1845:4294967293 shortened to 253
../x86-spentry64.s:1885:4294967291 shortened to 251
../x86-spentry64.s:1889:4294967291 shortened to 251
../x86-spentry64.s:1927:4294967291 shortened to 251
../x86-spentry64.s:1931:4294967291 shortened to 251
../x86-spentry64.s:2135:4294967293 shortened to 253
../x86-spentry64.s:2141:4294967293 shortened to 253
../x86-spentry64.s:2142:4294967293 shortened to 253
../x86-spentry64.s:2156:4294967293 shortened to 253
../x86-spentry64.s:2177:4294967293 shortened to 253
../x86-spentry64.s:2179:4294967293 shortened to 253
../x86-spentry64.s:2307:4294967283 shortened to 243
../x86-spentry64.s:2310:4294967291 shortened to 251
../x86-spentry64.s:2373:4294967293 shortened to 253
../x86-spentry64.s:2391:4294967293 shortened to 253
../x86-spentry64.s:2409:4294967293 shortened to 253
../x86-spentry64.s:2452:4294967293 shortened to 253
../x86-spentry64.s:2462:4294967289 shortened to 249
../x86-spentry64.s:2463:4294967289 shortened to 249
../x86-spentry64.s:2464:4294967283 shortened to 243
../x86-spentry64.s:2511:4294967291 shortened to 251
../x86-spentry64.s:2571:4294967293 shortened to 253
../x86-spentry64.s:2585:4294967289 shortened to 249
../x86-spentry64.s:2586:4294967289 shortened to 249
../x86-spentry64.s:2588:4294967283 shortened to 243
../x86-spentry64.s:2627:4294967293 shortened to 253
../x86-spentry64.s:2675:4294967293 shortened to 253
../x86-spentry64.s:2883:4294967291 shortened to 251
../x86-spentry64.s:2913:4294967291 shortened to 251
../x86-spentry64.s:2948:4294967293 shortened to 253
../x86-spentry64.s:2957:4294967293 shortened to 253
../x86-spentry64.s:2981:4294967291 shortened to 251
../x86-spentry64.s:3037:4294967283 shortened to 243
../x86-spentry64.s:3076:4294967293 shortened to 253
../x86-spentry64.s:3093:4294967293 shortened to 253
../x86-spentry64.s:3109:4294967293 shortened to 253
../x86-spentry64.s:3144:4294967293 shortened to 253
../x86-spentry64.s:3148:4294967293 shortened to 253
../x86-spentry64.s:3175:4294967283 shortened to 243
../x86-spentry64.s:3183:4294967293 shortened to 253
../x86-spentry64.s:3185:4294967293 shortened to 253
../x86-spentry64.s:3189:4294967291 shortened to 251
../x86-spentry64.s:3260:4294967293 shortened to 253
../x86-spentry64.s:3291:4294967283 shortened to 243
../x86-spentry64.s:3294:4294967283 shortened to 243
../x86-spentry64.s:3296:4294967287 shortened to 247
../x86-spentry64.s:3509:4294967283 shortened to 243
../x86-spentry64.s:3512:4294967283 shortened to 243
../x86-spentry64.s:3517:4294967291 shortened to 251
../x86-spentry64.s:3521:4294967291 shortened to 251
../x86-spentry64.s:3522:4294967299 shortened to 3
../x86-spentry64.s:3537:4294967283 shortened to 243
../x86-spentry64.s:3540:4294967283 shortened to 243
../x86-spentry64.s:3542:4294967291 shortened to 251
../x86-spentry64.s:3562:4294967283 shortened to 243
../x86-spentry64.s:3563:4294967291 shortened to 251
../x86-spentry64.s:3567:4294967283 shortened to 243
../x86-spentry64.s:3568:4294967291 shortened to 251
../x86-spentry64.s:3782:4294967291 shortened to 251
../x86-spentry64.s:3797:4294967299 shortened to 3
../x86-spentry64.s:3818:4294967307 shortened to 11
../x86-spentry64.s:3822:4294967315 shortened to 19
../x86-spentry64.s:3833:4294967323 shortened to 27
../x86-spentry64.s:3845:4294967331 shortened to 35
../x86-spentry64.s:3857:4294967339 shortened to 43
../x86-spentry64.s:3869:4294967347 shortened to 51
../x86-spentry64.s:3881:4294967355 shortened to 59
../x86-spentry64.s:3893:4294967363 shortened to 67
../x86-spentry64.s:3907:4294967283 shortened to 243
../x86-spentry64.s:3908:4294967283 shortened to 243
../x86-spentry64.s:3915:4294967291 shortened to 251
../x86-spentry64.s:3916:4294967291 shortened to 251
../x86-spentry64.s:3929:4294967291 shortened to 251
../x86-spentry64.s:3930:4294967291 shortened to 251
../x86-spentry64.s:3943:4294967283 shortened to 243
../x86-spentry64.s:3944:4294967283 shortened to 243
../x86-spentry64.s:3948:4294967291 shortened to 251
../x86-spentry64.s:3949:4294967291 shortened to 251
../x86-spentry64.s:3960:4294967291 shortened to 251
../x86-spentry64.s:3961:4294967291 shortened to 251
../x86-spentry64.s:3963:4294967295 shortened to 255
../x86-spentry64.s:3964:4294967295 shortened to 255
../x86-spentry64.s:3987:4294967283 shortened to 243
../x86-spentry64.s:3997:4294967283 shortened to 243
../x86-spentry64.s:4000:4294967291 shortened to 251
../x86-spentry64.s:4013:4294967293 shortened to 253
../x86-spentry64.s:4018:4294967293 shortened to 253
../x86-spentry64.s:4022:4294967379 shortened to 83
../x86-spentry64.s:4035:4294967283 shortened to 243
../x86-spentry64.s:4048:4294967387 shortened to 91
../x86-spentry64.s:4059:4294967293 shortened to 253
../x86-spentry64.s:4086:4294967293 shortened to 253
../x86-spentry64.s:4116:4294967411 shortened to 115
../x86-spentry64.s:4127:4294967419 shortened to 123
../x86-spentry64.s:4139:4294967427 shortened to 131
../x86-spentry64.s:4149:4294967443 shortened to 147
../x86-spentry64.s:4160:4294967451 shortened to 155
../x86-spentry64.s:4165:4294967283 shortened to 243
../x86-spentry64.s:4172:4294967467 shortened to 171
../x86-spentry64.s:4219:4294967435 shortened to 139
../x86-spentry64.s:4223:4294967283 shortened to 243
../x86-spentry64.s:4230:4294967459 shortened to 163
../x86-spentry64.s:4263:4294967291 shortened to 251
../x86-spentry64.s:4391:4294967283 shortened to 243
../x86-spentry64.s:4392:4294967291 shortened to 251
../x86-spentry64.s:4474:4294967291 shortened to 251
../x86-spentry64.s:4491:4294967291 shortened to 251
../x86-spentry64.s:4585:4294967283 shortened to 243
../x86-spentry64.s:4586:4294967291 shortened to 251
../x86-spentry64.s:4969:4294967283 shortened to 243
../x86-spentry64.s:4972:4294967291 shortened to 251
../x86-spentry64.s:4985:4294967283 shortened to 243
../x86-spentry64.s:5007:4294967283 shortened to 243
../x86-spentry64.s:5010:4294967291 shortened to 251
../x86-spentry64.s:5030:4294967283 shortened to 243
../x86-spentry64.s:5052:4294967283 shortened to 243
../x86-spentry64.s:5055:4294967291 shortened to 251
../x86-spentry64.s:5068:4294967283 shortened to 243
../x86-spentry64.s:5090:4294967283 shortened to 243
../x86-spentry64.s:5093:4294967291 shortened to 251
../x86-spentry64.s:5113:4294967283 shortened to 243
../x86-spentry64.s:5141:4294967283 shortened to 243
../x86-spentry64.s:5179:4294967291 shortened to 251
../x86-spentry64.s:5213:4294967291 shortened to 251
../x86-spentry64.s:5226:4294967291 shortened to 251
../x86-spentry64.s:5237:4294967291 shortened to 251
../x86-spentry64.s:5244:4294967291 shortened to 251
../x86-spentry64.s:5249:4294967323 shortened to 27
../x86-spentry64.s:5257:4294967283 shortened to 243
../x86-spentry64.s:5260:4294967275 shortened to 235
../x86-spentry64.s:5262:4294967267 shortened to 227
../x86-spentry64.s:5265:4294967323 shortened to 27
../x86-spentry64.s:5271:4294967283 shortened to 243
../x86-spentry64.s:5273:4294967275 shortened to 235
../x86-spentry64.s:5276:4294967283 shortened to 243
make: *** [x86-spentry64.o] Error 1

Secondly homebrew currently has 1.11.6 available for download and just wandering why are not the more recent versions available?

**Comment by willowell** [comment]
Hi, I got the same error while trying to rebuild the lisp kernel on macOS Catalina for the 1.12 version.

**Comment by willowell** [comment]
To be precise, I followed the installation directions: download the 1.12 source, unzip the image binary (darwinx86.tar.gz) into the 1.12 source directory, and then cd into the darwinx8664 kernel directory and rebuild it with `make clean` and `make`. `make` gives:
```
gm4 -DDARWIN -DX86 -DX8664 -DTCR_IN_GPR -I../ ../x86-spjump64.s | as -arch x86_64 -g -Q -o x86-spjump64.o
../x86-spjump64.s:unknown:rs_org invalid, dot past value by -17616 bytes
gm4 -DDARWIN -DX86 -DX8664 -DTCR_IN_GPR -I../ ../x86-spentry64.s | as -arch x86_64 -g -Q -o x86-spentry64.o
../x86-spentry64.s:55:4294967283 shortened to 243
```
and then several lines similar to the last one, with this in the middle:
```
../x86-spentry64.s:1184:suffix or operands invalid for `movq'
../x86-spentry64.s:1184:4294967291 shortened to 251
../x86-spentry64.s:1190:suffix or operands invalid for `movq'
../x86-spentry64.s:1190:4294967291 shortened to 251
../x86-spentry64.s:1205:suffix or operands invalid for `movq'
../x86-spentry64.s:1205:4294967291 shortened to 251
../x86-spentry64.s:1211:suffix or operands invalid for `movq'
```

**Comment by xrme** [comment]
Please update to Xcode 11.4 or later.

See #271

**Comment by willowell** [comment]
🤦 I forgot to check my Xcode version. No problems now. Thank you!
