### ISSUE TITLE
Clozure won't print any text in cmd

### ISSUE THREAD

**Issue by cwchentw** [Clozure/ccl#287]
Clozure CL version: 1.11.5
Windows version: Windows 10 ver1909

Sample program:

```lisp
(defun main ()
  (write-line "Hello World")
  (#_exit 0))

(main)
```

Due to Clozure CL issue, I use `(#_exit 0)` instead of `(quit)`.

**Comment by phoe** [comment]
What happens if you `(finish-output)` before exiting?

**Comment by cwchentw** [comment]
It works when adding `(finish-output)` in the above script.

**Comment by phoe** [comment]
Not a CCL issue then. The standard allows IO to be buffered by the implementation, and `(finish-output)` flushes the buffers. That is why you see nothing printed to the console.

**Comment by cwchentw** [comment]
It didn't happen last week. Hence, I thought it was a CCL issue. Anyway, it works now. Thanks a lot.

**Comment by xrme** [comment]
It's true that CCL will auto-flush certain streams (in a periodic task that runs about three times a second).  But it might not get the chance it to do that between the the `write-line` and the `#_exit`.  Using `finish-output` is the correct (and standard-conforming) way to go.
