### ISSUE TITLE
Backport MS Windows fix to 1.11 branch

### ISSUE THREAD

**Issue by snunez1** [Clozure/ccl#288]
Merge #233 fixes the MS Windows hanging problem, but is only available on master (1.12).

**Comment by xrme** [comment]
I'll cherry-pick it to the 1.11 branch and make new binaries this week.

**Comment by xrme** [comment]
Did I ever do this? If not, do I still want/need to fix the 1.11 branch?

**Comment by snunez1** [comment]
It was never done, and since it's easy I'd suggest doing it so there's an alternative to 1.12, just in case.

**Comment by xrme** [comment]
Cherry-picked the fix for #233 (ce4a8543684effdd612789f3f2fbcddcaab7de51) to the 1.11 branch (as 55ebe5d5bda41b6a3bb0b4e999561f0b9f4f8ec5).
