### ISSUE TITLE
Clozure easily bombs to AltConsole with simple and common text operations in the Listener

### ISSUE THREAD

**Issue by eclab** [Clozure/ccl#292]
**Example 1**

1. Launch Clozure CL (MacOS).
1. Go to the Listener.
1. Press Command-Z (Undo).
1. BOMB

**Example 2**

1. Launch Clozure CL (MacOS).
1. Go to the Listener.
1. Select the Listener's welcome text.  For me, this is the text "Welcome to Clozure Common Lisp Version 1.11-store-r16714  (DarwinX8664)!CCL is developed and maintained by Clozure Associates. For more information about CCL visit http://ccl.clozure.com.  To enquire about Clozure's Common Lisp consulting services e-mail info@clozure.com or visit http://www.clozure.com."
1. Command-C (Copy)
1. Click once in the "protected buffer region" (the little message space at the bottom of the window)
1. Command-V (Paste)
1. BOMB

It is very poor UI to offer an operation (Undo, Paste) and then bomb when the user selects it.  Instead, that option should not be offered in the first place in the situations where it won't work properly.  The AltConsole should never be launched, *ever*, in response to standard GUI operations.  I accidentally do this stuff constantly, and it is so bad that I have nearly given up on CCL in comparison to Slime.  :-(  And I'm an old-time MCL user.

**Comment by xrme** [comment]
The Mac App Store version of CCL is broken and has been removed from the store.

If you can download the latest release and build the IDE locally with `(require 'cocoa-application)`, that's the way to go.
