### ISSUE TITLE
MacPorts ccl-1.12 progress

### ISSUE THREAD

**Issue by easye** [Clozure/ccl#294]
Congratulations on finally blessing something as ccl-1.12! 

For getting MacPorts in line, I am stuck on the error referenced in <https://trac.macports.org/ticket/60377>.  

I'll work on it as I can, but at least wanted to flag it here for more experienced Clozure-heads to have a chance to ponder.

**Comment by xrme** [comment]
This sounds suspiciously like #289, which I assumed was only on Catalina, but I didn't actually check.

**Comment by easye** [comment]
> This sounds suspiciously like #289, which I assumed was only on Catalina, but I didn't actually check.

Indeed, that worked for me.  For the record, I have gotten this working on macOS 10.15 Catalina, as I had to upgrade my development machine's XCode for mobile development.

With <https://github.com/macports/macports-ports/commit/6e8dcf5b19bd6a31a175096f9b4dfdcb63326930>, MacPorts now has a build recipe for ccl-1.12.
