### ISSUE TITLE
Keep file name convention.

### ISSUE THREAD

**Issue by snmsts** [Clozure/ccl#295]
**Please** have file name convention.

why change previous convention?
https://github.com/Clozure/ccl/releases/download/v1.12/darwinx86.tar.gz for 1.12 and
https://github.com/Clozure/ccl/releases/download/v1.11.5/ccl-1.11.5-darwinx86.tar.gz for 1.11.5?
I know it's nothing for manual installation. but I'm making tool to support ccl. **please** consider.

**Comment by xrme** [comment]
What conventions do I need to preserve?  Are you looking for a single tar archive with complete sources and binaries, like we have distributed in the past?  Do you need the tar archive to contain a complete copy of the git repository, or should it contain only exported sources?

**Comment by snmsts** [comment]
Thank you for consideration.

for roswell's requirement is just
* archivefile name should be named with ccl-(version)-(os)(arch).(tar.gz or zip) instead of (os)(arch).(tar.gz or zip)
* when it is extracted. executable (l|w|d|f|s)?(x86|arm)cl(32|64)(.exe)? and image file under ccl.

>> a single tar archive with complete sources and binaries
no, roswell couldn't support ccl source installation.it doesn't care other than executable and image file.
I want to support more but self hosted compilation and ccl's version restriction for compile is a bit complicated to understand/test enough yet for me for now.

**Comment by guicho271828** [comment]
Note that, as a library author, if ccl on roswell breaks, then all of the Travis-CI builds breaks. The entire quicklisp repos may collapse.

**Comment by xrme** [comment]
What about things like the bundled ASDF or the interface database so that the `#_` macro works?   Do you really just want the lisp kernel and and the heap image?

**Comment by mdbergmann** [comment]
> Note that, as a library author, if ccl on roswell breaks, then all of the Travis-CI builds breaks. The entire quicklisp repos may collapse.

That sounds like there is not enough decoupling

**Comment by snmsts** [comment]
@xrme It's out of focus here at least for me. I mean I respect author's decision for that kind.
I guess official archive already have cared enough for users which expects compatibility. I'm sorry if you feel something about this part.

There might be confusion about what I want.
Practically what I want in this context is just repack archives for this release.

```
$ mkdir ccl
$ cd ccl
$ curl -L -O https://github.com/Clozure/ccl/releases/download/v1.12/darwinx86.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   627  100   627    0     0   1140      0 --:--:-- --:--:-- --:--:--  1137
100 18.0M  100 18.0M    0     0  1782k      0  0:00:10  0:00:10 --:--:-- 2882k
$ tar xf darwinx86.tar.gz 
$ cd ..
$ tar czf ccl-1.12-darwinx86.tar.gz  ccl/
```

and this ccl-1.12-*.tar.gz (zip for windows) is what I expect to have.
Why I have this issue is ask ccl maintainer's to keep same structure for the future releases.
There could be structure change if reasonable,but It seems there's no drawback to keep same structure.

**Comment by guicho271828** [comment]
> > Note that, as a library author, if ccl on roswell breaks, then all of the Travis-CI builds breaks. The entire quicklisp repos may collapse.
> 
> That sounds like there is not enough decoupling

If you want to keep things decoupled, then the "interface" must be consistent. Interface being, the interface to obtain, uncompress, and run CCL. Roswell has been working on 1.11 and 1.11.5, thus it is decoupled from CCL versions, as long as CCL kept the "interface".

**Comment by guicho271828** [comment]
![Screenshot from 2020-04-24 14-55-54](https://user-images.githubusercontent.com/1321968/80247270-c4225c00-863b-11ea-970c-0d67c3c7efd8.png)

**Comment by xrme** [comment]
I'm happy to add re-packed archives in the format that Roswell wants.

I was just trying to understand exactly what in the archive it is relying on. If Roswell doesn't care about source code or the git repository, then I thought it would be good to leave that out of the archive to save time and bandwidth, but maybe the best thing to do is just to make archives with source and git repository like I was doing before.

**Comment by 3b** [comment]
Using ccl through roswell for CI, I'd like to see at least the bundled asdf and interface database (and anything else likely to be useful at runtime, if any) in the archive. Reduced bandwidth sounds nice for that, but I try to set CI builds to cache it if possible. and I'm not paying for the bandwidth anyway :)

If I were using ccl through roswell for development, ccl source would probably also be useful for M-. in slime. I probably wouldn't expect a git repo in a tarball, usually I'd clone manually if I wanted that.

Source + whatever is needed to run things from QL is probably a reasonable compromise if you want to make something smaller, but just keeping existing package contents is fine too.

**Comment by snmsts** [comment]
@xrme Are there problem still?

**Comment by xrme** [comment]
I put in archives for Darwin, Linux, and Windows.  Would you please give them a brief test and let me know if they are in the expected format?  If so, I'll add the remaining ports.

**Comment by snmsts** [comment]
https://travis-ci.org/github/roswell/roswell/jobs/685916486 looks work fine.

**Comment by svetlyak40wt** [comment]
Great! Now it works  on my OSX!

**Comment by snmsts** [comment]
arm left? (sorry I don't have Solaris/FreeBSD box)

**Comment by xrme** [comment]
The archives for 1.12.2 should be in the usual format.
