### ISSUE TITLE
CCL 1.12 broke roswell because of different file packaging

### ISSUE THREAD

**Issue by f2l2pe** [Clozure/ccl#296]
Hi, i was trying to install the new CCL version with roswell but its breaking it
The reason was that the structure of the packaging changed

CCL 1.11.8:
```
Zip file 
    ccl 
        files...
```
CCL 1.12
```
Zip file
    files....
```

Is it possible to maintain the package structure so it doesnt break older implementations?

**Comment by xrme** [comment]
Is this the same as #295?  I didn't know tools were relying on the names and structure of the release archives.

**Comment by chiniara** [comment]
> Is this the same as #295? I didn't know tools were relying on the names and structure of the release archives.

Yes, it indeed looks about the same, but the issue name confused me.

**Comment by xrme** [comment]
The archives I built for the 1.12.2 release should be in the usual format.
