### ISSUE TITLE
(describe 'some) doesn't show documentation as in SBCL

### ISSUE THREAD

**Issue by mdbergmann** [Clozure/ccl#297]
HI.

I'm running the new CCL 1.12.
Playing around a bit I was wondering why CCL doesn't show the documentation as SBCL does.

I.e.:
CCL
```
? (describe 'cl-gserver.actor:actor)
ACT:ACTOR
Type: SYMBOL
Class: #<BUILT-IN-CLASS SYMBOL>
Type Specifier, Class Name
EXTERNAL in package: #<Package "CL-GSERVER.ACTOR">
Print name: "ACTOR"
Value: #<Unbound>
Function: #<Unbound>
Plist: NIL
Class: #<STANDARD-CLASS ACT:ACTOR>
```

Same symbol in SBCL:
```
* (describe 'cl-gserver.actor:actor)
CL-GSERVER.ACTOR:ACTOR
  [symbol]

ACTOR names the standard-class #<STANDARD-CLASS CL-GSERVER.ACTOR:ACTOR>:
  Documentation:
    Specialized `gserver' class called `actor'.
    There is a different terminology behind `actor'.
    I.e. There is only one `receive' function.
    And there is asynchronous `send' and synchronous `ask'.
    So there is not much difference to a `gserver'.
    It only uses one method `receive'. However both `handle-call' and `handle-cast' og `gserver'
    end up in `receive'.
  Direct superclasses: GS:GSERVER
  Direct subclasses: ACT::SIMPLE-ACTOR
  Not yet finalized.
  No direct slots.
```

Similar is with `standard-class` where CCL doesn't show a lot but SBCL shows class precendence-list, etc.

Why doesn't CCL show the documentation?

**Comment by xrme** [comment]
The output of describe is totally implementation dependent.

There's no profound reason why CCL doesn't show documentation and CLOS info like SBCL does.  It just wasn't implemented that way.  It would, of course, be possible to make CCL's describe show more stuff.

**Comment by svspire** [comment]
Try `(describe (find-class 'cl-gserver.actor:actor))`. You'll see a lot more information.

If you use the IDE version of CCL on the Mac, you can do
`(inspect 'cl-gserver.actor:actor)` and click your way through the object. This is much more useful than `describe`.

**Comment by phoe** [comment]
CCL's `describe` does mention that `actor` names a class:
```
Class: #<STANDARD-CLASS ACT:ACTOR>
```

It simply doesn't recurse into it and describe the class object. That's allowed - as @xrme mentioned, `describe` is implementation-dependent, and *could* be perhaps modified if we really want it to be.

**Comment by mdbergmann** [comment]
> Try (describe (find-class 'cl-gserver.actor:actor)). You'll see a lot more information.

It shows more information, but not the custom class documentation.

**Comment by mdbergmann** [comment]
OK, I would close this.

It seems the standard way of retrieving documentation is the `documentation` method.

However I must admit, that SBCL's `describe` is very handy.
