### ISSUE TITLE
CCL1.12, CCL1.11 ccl-tests ccl.bug#1068.a fails on Windows

### ISSUE THREAD

**Issue by gendl** [Clozure/ccl#298]
Hi,
 
 As stated in subject. The failure boils down to a confusion with `pathname-directory` on windows for the pathname `"a*x+b.rtfd"` where the Lisp string representation of this in the test is `"a\\*x+b.rtfd"`, and CCL's `pathname-directory` is apparently seeing that backslash as indicating a directory separator. 

I'm not really sure if this is a bug in Windows CCL or a bug in the test. 

Anyone more familiar with this and can shed some light? 

Thanks,

 Dave

**Comment by xrme** [comment]
The whole scheme of trying to escape certain characters in namestrings is a long-standing source of confusion and annoyance.

See https://trac.clozure.com/ccl/ticket/632

**Comment by xrme** [comment]
Windows doesn't allow `#\*` chars in file/dir names. We now exclude the test `ccl.bug#1068.a` on Windows.

(see https://github.com/Clozure/ccl-tests/commit/f803673094b439b004f7615e3f4089ec0d2659e9)
