### ISSUE TITLE
PPRINT-DISPATCH violates clhs.

### ISSUE THREAD

**Issue by hyotang666** [Clozure/ccl#314]
? (lisp-implementation-version)
"Version 1.12 (v1.12) LinuxX8664"
? (pprint-dispatch t nil)
> Error: The value NIL is not of the expected type STRUCTURE.
> While executing: CCL::GET-PRINTER, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
1 > :q

[CLHS says](http://www.lispworks.com/documentation/HyperSpec/Body/f_ppr_di.htm)

> table---a pprint dispatch table, or nil.

**Comment by kpoeck** [comment]
Seems to be fixed with:
```lisp
(defun pprint-dispatch (object &optional (table *print-pprint-dispatch*))
  (flet ((non-pretty-print (s object)
           (write-not-pretty s object
                             (if (get-*print-frob* '*print-level*)
                               (- *print-level* *current-level*))
                             nil nil)))
    (let ((fn (get-printer object (or table *standard-pprint-dispatch-table*))))
      (values (or fn #'non-pretty-print) (not (null fn))))))
````

If nobody objects, will make a pr

**Comment by hyotang666** [comment]
[CLHS says](http://www.lispworks.com/documentation/HyperSpec/Body/f_ppr_di.htm)

> If table is nil, retrieval is done in the initial pprint dispatch table. 

[and](http://www.lispworks.com/documentation/HyperSpec/Body/26_glo_i.htm#initial_pprint_dispatch_table)

> initial pprint dispatch table n. the value of *print-pprint-dispatch* at the time the Lisp image is started. 

so `(copy-pprint-dispatch nil)` will be used rather than `*print-pprint-dispatch*` to bind &optional table.

**Comment by kpoeck** [comment]
If you are trying to say `(copy-pprint-dispatch nil)`should be used instead of `*standard-pprint-dispatch-table*`, you are wrong, since `*standard-pprint-dispatch-table*`is the value of *print-pprint-dispatch* when the image was started.

If you have another fix in mind, please state it clearly

**Comment by hyotang666** [comment]
Oh, I'm sorry, I was wrong.
I confused `*standard-pprint-dispatch-table*` and `*print-pprint-dispatch*`.

**Comment by kpoeck** [comment]
ok, than I create the fix
