### ISSUE TITLE
Linking error under Arch Linux

### ISSUE THREAD

**Issue by stefanhusmann** [Clozure/ccl#317]
Unter Arch Linux I get the following
[buildlog.txt](https://github.com/Clozure/ccl/files/4676344/buildlog.txt)

I used the PKGBUILD in AUR https://aur.archlinux.org/packages/ccl-git/ , but I also treide to build a kernel with the workaround described in the announcement for windows and catalina, with no success.

**Comment by phoe** [comment]
Fixed by https://github.com/Clozure/ccl/pull/316

**Comment by stefanhusmann** [comment]
Indeed, thanks.

**Comment by phoe** [comment]
This is merged to master right now - is there any other problem related to this issue? If not, we could perhaps close it.
