### ISSUE TITLE
Defined package-local-nicknames are not shown in Emacs code-completion

### ISSUE THREAD

**Issue by mdbergmann** [Clozure/ccl#323]
See attached screenshots.

Not sure if this is as designed or if this is related to CCL.
However, nicknames are shown OK as completion in SBCL.
And I'm assuming that that should be the case also for CCL.

In the images as example 'trivia' where a local nickname was setup as 'tr'.

<img width="363" alt="ccl-plnn-2" src="https://user-images.githubusercontent.com/2143978/83954349-9f2f2480-a848-11ea-86a2-fd6ede552e77.png">
<img width="352" alt="sbcl-plnn-2" src="https://user-images.githubusercontent.com/2143978/83954353-a1917e80-a848-11ea-850f-0d6bf9dd2f6b.png">
<img width="403" alt="sbcl-plnn-1" src="https://user-images.githubusercontent.com/2143978/83954354-a22a1500-a848-11ea-9456-85a583b06e7d.png">
<img width="424" alt="ccl-plnn-1" src="https://user-images.githubusercontent.com/2143978/83954355-a2c2ab80-a848-11ea-9c03-d4abe5af8137.png">

**Comment by xrme** [comment]
I'd assume that's an issue with whatever Emacs interface you are using.

**Comment by mdbergmann** [comment]
I'm using Sly. So the backend for Sly in Slynk and that gets its data from the Lisp implementation.
It would be surprising if Sly/Slynk behaves different depending on which Lisp impl is uses.
But, I'll check on that.

**Comment by phoe** [comment]
>  It would be surprising if Sly/Slynk behaves different depending on which Lisp impl is uses.

Obviously it does so! Slynk is a portability library and works differently on different Lisp implementations.

See https://github.com/joaotavora/sly/search?q=package-local-nicknames&unscoped_q=package-local-nicknames - only SBCL, ECL, and ABCL have PLN implementations for them. Sly needs to define one for CCL.

@xrme Closeable - not a CCL issue.

**Comment by xrme** [comment]
I'll close this as not being a CCL bug. If Slynk wants new features in CCL, let's talk about those in other issues.

**Comment by mdbergmann** [comment]
OK, thanks for the clarification.
That seems to be straight forward to add in Slynk.

**Comment by phoe** [comment]
Yep.

```lisp
#+#.(slynk-backend:with-symbol 'package-local-nicknames 'ccl)
(defimplementation package-local-nicknames (package)
  (ccl:package-local-nicknames package))
``
