### ISSUE TITLE
ccl::conditional-store doesn't work on typed struct accessors

### ISSUE THREAD

**Issue by sionescu** [Clozure/ccl#326]
Minimal test case:

(defstruct af
  (value 0 :type fixnum))

(defun af-cas (af old new)
  (declare (type af af)
           (type fixnum old new)
           (optimize (safety 0) (speed 3)))
  (ccl::conditional-store (af-value af) old new))

;Compiler warnings for "home:work;src;bordeaux-threads;apiv2;ccl-cas-error.lisp.newest" :
;   In AF-CAS: Don't know how to do conditional store to (THE FIXNUM (CCL::STRUCT-REF (CCL::STRUCTURE-TYPECHECK AF AF) 1))
;   In AF-CAS: Unused lexical variable NEW
;   In AF-CAS: Unused lexical variable OLD
;   In AF-CAS: Unused lexical variable AF

**Comment by eugeneia** [comment]
I remember running into this or a related issue. IIRC I worked around this by implementing conditional store like this:

https://github.com/eugeneia/erlangen/commit/484e3fd018782087eecb0764b4c4859b1150fe1f#diff-18b7d64ce80a2598512744758ea93c8eR14-R46

**Comment by eugeneia** [comment]
I.e., I think the relevant change is that I added a [clause](https://github.com/eugeneia/erlangen/blob/cas/ccl.lisp#L32-L34) to handle `THE` forms.

```
      (if (eq (car place) 'the)
        (setq place (caddr place)
              sym (car place)))
```
