### ISSUE TITLE
Trouble with networking

### ISSUE THREAD

**Issue by pebblexe** [Clozure/ccl#33]
I have been working on [a project called cl-wamp](https://github.com/pebblexe/cl-wamp) for a while and just recently discovered that these weird connection issues I was having were due to ccl (they stopped when I switched to sbcl).

I'm not sure what's causing it, but I know that commenting out lines 127 and 128 seems to fix it sometimes.

I think it's a really weird heisenbug, but I could also just be an idiot.

I'm using 1.11-r16635  (LinuxX8664).

**Comment by eugeneia** [comment]
Hi @pebblexe 

I am afraid you will have to be more specific than “lines 127 and 128”, do you mean this line (and the following)? https://github.com/pebblexe/cl-wamp/blob/master/cl-wamp.lisp#L127

Please construct a test case that can easily be reproduced (i.e. a file that we can load to run into the error).

**Comment by pebblexe** [comment]
You are absolutely right, I should have created a minimal example of the bug. I guess I wasn't really thinking. I'll do that today.

Also that is indeed the line that seems to affect whether or not any messages are received.

**Comment by pebblexe** [comment]
It turns out it was my fault.

**Comment by xrme** [comment]
Well, glad you found the problem, anyway.
