### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by GOFAI** [Clozure/ccl#330]
Given the announcement at WWDC 2020 that macOS is transitioning to ARM, it seems that ARM64 support is going to become much more important pretty soon. I see that there are the beginnings of ARM64 support in the source tree--how far did that effort get, and does anyone have a sense of how much effort will be required to get it working?

There's also the question of whether the Intel version of CCL will run correctly on ARM macs using Rosetta 2. Is anyone planning on ordering one of the ARM developer machines Apple announced who could check?

**Comment by xrme** [comment]
I applied to get one.

**Comment by eschaton** [comment]
Since macOS running on Apple Silicon builds for the `arm64` architecture, this is a semi-dup of #11. However that could also cover (say) Linux, FreeBSD, or NetBSD on arm64.

**Comment by GOFAI** [comment]
Now that production ARM Macs have been announced the matter of CCL support for them is becoming more pressing. Is there any written guidance about the process of porting CCL to a new architecture? Can the work be split up into parts and farmed out? I'd like to assist such as I am able to, given my (modest) capabilities.

**Comment by xrme** [comment]
duplicates #11
