### ISSUE TITLE
CCL not starting in Aquamacs using slime

### ISSUE THREAD

**Issue by JanMarinus** [Clozure/ccl#339]
I have installed Aquamacs 3.5, Slime, loaded through Melpa, initialised for CCL 1.11.5 on Macbook Catalina 10.15.6. I have compiled the lisp kernel binary.
When starting M-x slime I get this response:
(progn (load "/Users/jvdsmacbook/Library/Preferences/Aquamacs Emacs/Packages/elpa/slime-20200721.1604/swank-loader.lisp" :verbose t) (funcall (read-from-string "swank-loader:init") :from-emacs t) (funcall (read-from-string "swank:start-server") "/var/folders/96/cxqfcbbx0n38n20x9hss8yxr0000gn/T/slime.27376"))

Clozure Common Lisp Version 1.11.5/v1.11.5  (DarwinX8664)

For more information about CCL, please see http://ccl.clozure.com.

CCL is free software.  It is distributed under the terms of the Apache
Licence, Version 2.0.
? ;Loading #P"/Users/jvdsmacbook/Library/Preferences/Aquamacs Emacs/Packages/elpa/slime-20200721.1604/swank-loader.lisp"...sigreturn returned
? for help
[27385] Clozure CL kernel debugger: 

I have contacted the slime community, they referred to a failing CCL generating the debugger. Any idea on the cause of this?

**Comment by phoe** [comment]
1.11.5 is too old to work on Catalina. Have you tried a more recent release?

https://github.com/Clozure/ccl/releases

**Comment by kpoeck** [comment]
I have clozure working fine in aquamacs 3.5 with "Version 1.12 (v1.12-dev.3-125-g595a5cf4) DarwinX8664" and mojave 10.14.6, so pretty sure this is a catalina/ccl issue independent from slime.

There are several descriptions how to build ccl on catalina, will try to find the latest

**Comment by kpoeck** [comment]
Please check https://github.com/Clozure/ccl/issues/285

**Comment by JanMarinus** [comment]
Dear Karsten,

Thank you for your help. 1.12 works flawless. Problem Fixed.

Best regards, Jan
