### ISSUE TITLE
Error: Foreign function not found: ARM-LINUX::|gethostname|

### ISSUE THREAD

**Issue by TurretAA12** [Clozure/ccl#340]
Hello,
For some context I am trying to build pgloader using CCL, due to the fact CCL supports threading on ARM32.  While trying to do this I have overcame numerous issues (with the help of @phoe) which you can see documented [here](https://github.com/dimitri/pgloader/issues/1101). 

Now I reach another roadblock. When building I get the following error: ⬇
```
[package usocket]..............
Read error between positions 66 and 163 in /home/pi/pgloader/build/quicklisp/dists/quicklisp/software/usocket-0.8.3/backend/openmcl.lisp.
> Error: Foreign function not found: ARM-LINUX::|gethostname|
> While executing: CCL::LOAD-EXTERNAL-FUNCTION, in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip evaluation of (ql:quickload "pgloader")
> Type :? for other options.
1 >
```

I tried using the [`gethostname` function](https://docs.python.org/3/library/socket.html#socket.gethostname) in Python (which I believe is the same 'foreign function' mentioned in the error message above) to see if this a CCL problem or a Linux problem and it appears to be an issue with CCL.  The Python script ran with no issue.
Here's my Python script: ⬇
```python
>>> import socket
>>> socket.gethostname()
'raspberrypi'
```
I would greatly appreciate if anyone knows a possible solution. [This might be a related issue](https://github.com/cl-test-grid/cl-test-grid/issues/31).

**Comment by svspire** [comment]
This is not a CCL problem, it's a usocket problem, because it was likely never tested on ARM Linux. If you define get-host-name in usocket as

`(defun get-host-name ()
  (machine-instance))`

it should just work. Usocket has lots of problems; you might run into others.

**Comment by TurretAA12** [comment]
Thank you for your reply.  I am new to CCL and don't know where the `usocket` file is.  Where can I find the `usocket` file?

**Comment by svspire** [comment]
According to your error message, it's at
`/home/pi/pgloader/build/quicklisp/dists/quicklisp/software/usocket-0.8.3/backend/openmcl.lisp`.

**Comment by TurretAA12** [comment]
Thank you very much for your help, your suggestion solved the issue. (Although there is a now another non-related CCL issue 😢). I will go ahead and close this issue.

**Comment by mdbergmann** [comment]
> According to your error message, it's at
> `/home/pi/pgloader/build/quicklisp/dists/quicklisp/software/usocket-0.8.3/backend/openmcl.lisp`.

Since usocket is a third-party library you might wanna file a bug here: https://github.com/usocket/usocket
