### ISSUE TITLE
Update the website's Downloads page, to reflect the current version

### ISSUE THREAD

**Issue by steve-perkins** [Clozure/ccl#347]
At the moment, the current version shown on [the website's downloads page](https://ccl.clozure.com/download.html) is 1.11.5.  

The **actual** current version, on [the GitHub releases page](https://github.com/Clozure/ccl/releases), is 1.12.0.  I stumbled across it due to a tip from the Common Lisp discord chat.

IDEALLY, it would be great to cut a new release first... since CCL is currently broken on Windows 10 machines with the latest patches (see issue #345).  But either way, please update the website to be in-line with the latest release in GitHub (or maybe just re-work that page altogether, to point people toward the GitHub releases page rather than manually-duplicated download links?).  Thanks!

**Comment by xrme** [comment]
I changed the downloads page to point to the GitHub release page.
