### ISSUE TITLE
defun lambda considers &optional an argument, not a keyword

### ISSUE THREAD

**Issue by snunez1** [Clozure/ccl#351]
I'm writing a library that shadows some functions in CL, so am not using (:use) CL in the package definition. However when doing this, CCL complains "Unused lexical variable &OPTIONAL". This can be reproduce as follows:

```
(cl:defpackage :opt-test
  (:use))

(cl:in-package :opt-test)

(cl:defun foo (x &optional bar)
  (cl:values))
```

and compiling the file.

This doesn't happen if the package is defined with (:use :cl), or if the :use clause is left out altogether.

Any ideas?

**Comment by phoe** [comment]
```lisp
(cl:defun foo (x cl:&optional bar)
  (cl:values))
```

`&optional` is a symbol in CL like any other; it is possible to have `foo:&optional` which will not be recognized as a lambda list keyword.
