### ISSUE TITLE
clozure-1.12 does not build with Xcode 12

### ISSUE THREAD

**Issue by danielnachun** [Clozure/ccl#354]
I am currently trying to get `clozure-1.12` to build for Homebrew: https://github.com/Homebrew/homebrew-core/pull/66944.  The build fails with the following error:

>==> ./dx86cl64 -n -l lib/x8664env.lisp -e (ccl:xload-level-0) -e (ccl:compile-ccl) -e (quit)
Couldn't load lisp heap image from /private/tmp/clozure-cl-20201215-39588-k9otsf/ccl-1.12/dx86cl64.image: Cannot allocate memory

This heap image needs to be built with an assembler, and currently the only option I'm aware of is the assembler shipped with the Xcode Command Line Tools.  In Xcode 12, it seems Apple has made some changes to the assembler:

>The stand-alone system assemblers for i386, x86_64, and arm are deprecated. Using the as command with the -Q flag shows a warning that instructs you to transition to Clang’s integrated assembler and the -q flag. The as(1) driver will remain, as a standard way to invoke Clang’s integrated assembler, as well as any assemblers installed by the developer. (61299833)

Could this change explain the error we're getting?  Xcode 12 was released in mid-September, while `clozure-1.12` was released in April, so it's possible nobody has tried to build the heap image with Xcode 12 yet.  It should be possible to reproduce this by just trying to build the heap image on a Mac with Xcode 12 installed.   Please let me know if any other information is needed!

**Comment by gmpalter** [comment]
You need to apply https://github.com/Clozure/ccl/commit/553c0f25f38b2b0d5922ca7b4f62f09eb85ace1c before building the kernel.

**Comment by danielnachun** [comment]
Thank you for the quick response!
