### ISSUE TITLE
rebuild with Xcode 12.4 fails.

### ISSUE THREAD

**Issue by informatimago** [Clozure/ccl#363]
I'm trying to compile git HEAD (with release binaries https://github.com/Clozure/ccl/releases/download/v1.12/ccl-1.12-darwinx86.tar.gz) on macOS Catalina 10.15.7 and Xcode 12.4, and it fails.

[ccl-rebuild.log](https://github.com/Clozure/ccl/files/6273569/ccl-rebuild.log)

```
> Error: Error(s) during kernel compilation.
>        make: Entering directory '/usr/local/src/ccl-git/lisp-kernel/darwinx8664'
>        gm4 -DDARWIN -DX86 -DX8664 -DTCR_IN_GPR -I../ ../x86-spjump64.s | as -arch x86_64 -g -Q -o x86-spjump64.o
>        gm4 -DDARWIN -DX86 -DX8664 -DTCR_IN_GPR -I../ ../x86-spentry64.s | as -arch x86_64 -g -Q -o x86-spentry64.o
>        gm4 -DDARWIN -DX86 -DX8664 -DTCR_IN_GPR -I../ ../x86-subprims64.s | as -arch x86_64 -g -Q -o x86-subprims64.o
>        gm4 -DDARWIN -DX86 -DX8664 -DTCR_IN_GPR -I../ ../imports.s | as -arch x86_64 -g -Q -o imports.o
>        cc -include ../platform-darwinx8664.h -c ../pmcl-kernel.c -arch x86_64 -DDARWIN -DX86 -DX8664 -DTCR_IN_GPR -DVC_REVISION="v1.12-39-g6c1a9458" -DUSE_DTRACE \
>        -g -O -Wno-format  \
>         -I. -mmacosx-version-min=10.9 -o pmcl-kernel.o
>        ../x86-spentry64.s:55:4294967283 shortened to 243
>        ../x86-spentry64.s:60:4294967291 shortened to 251
>        ../x86-spentry64.s:77:4294967283 shortened to 243
>        ../x86-spentry64.s:78:4294967291 shortened to 251
...
```

I will try to get an Xcode 11...

**Comment by xrme** [comment]
That sounds just like #271 again.

**Comment by gmpalter** [comment]
I just tried with Xcode 12.4 on macOS Big Sur 11.2.3 and the kernel builds without problem.

**Comment by informatimago** [comment]
In that case, I will upgrade to Big Sur. I was blocking this upgrade for ccl...

**Comment by metayan** [comment]
Building CCL from master on Catalina with command line tools works fine here.
(Might be good to know for those who will not "upgrade" to Big Sur.)

**Comment by informatimago** [comment]
It fails with Xcode-11.7 on Catalina 10.15.7 too.

**Comment by informatimago** [comment]
After upgrading to Big Sur, the rebuild still failed.  The reason why, seem to be the use of gm4 which was shadowed by a local one in /opt/local/bin; therefore I would suggest specifying a PATH in the directives to rebuild:

```
tar xf ../darwinx86.tar.gz && \
PATH=/usr/X11R6/bin:/usr/X11/bin:/usr/bin:/usr/sbin:/bin:/sbin ./dx86cl64  -n -e '(rebuild-ccl :full t)' 
```

This way, the rebuild works correctly on Big Sur (and I would assume in Catalina too), with Xcode 12.4.

**Comment by informatimago** [comment]
The documentation could also mention that after rebuilding a new version from git, with the same release (1.12), it might be worth removing the cache, since the fasl files may be incompatible:

```
rm -rf ~/.cache/common-lisp/ccl-1.12-*/
```

**Comment by metayan** [comment]
On Catalina, a full rebuild like
```sh
PATH=/usr/X11/bin:/usr/bin:/usr/sbin:/bin:/sbin ./dx86cl64 -n -e '(rebuild-ccl :full t)' 
```
fails with
```
;Building lisp-kernel ...
> Error: Error(s) during kernel compilation.
```

However, separating the steps as
```sh
pushd lisp-kernel/darwinx8664/
PATH=/usr/X11/bin:/usr/bin:/usr/sbin:/bin:/sbin make
popd
PATH=/usr/X11/bin:/usr/bin:/usr/sbin:/bin:/sbin ./dx86cl64 -n -e '(rebuild-ccl)'
```
works fine.

Also
```sh
PATH=/usr/X11/bin:/usr/bin:/usr/sbin:/bin:/sbin ./dx86cl64 -n -e '(require "cocoa-application")'
```
afterwards builds the application correctly.
