### ISSUE TITLE
scigraph ends up with SIMPLE-ERROR

### ISSUE THREAD

**Issue by saufesma** [Clozure/ccl#379]
$ ./lx86cl64 --version
Version 1.12 (v1.12) LinuxX8664

(ql:quickload "scigraph")
(in-package :graph)
(setq raw-data '((0 0) (1 -1.5) (2 3) (3 22) (4 8) (5 22)))
(setq dataset (make-instance 'graph-data
:symbologies '(:line-symbol)
:data raw-data))
(setq graph
(make-instance 'annotated-graph
:title "Some Data"
:x-label "Fortnights"
:y-label "Furlongs"))
(add-dataset graph dataset)
(view-graphs (list graph))

Stream #<BASIC-FILE-BINARY-INPUT-STREAM ("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"/7 ISO-8859-1) #x302005C8D58D> is private to #<PROCESS Frame Top Level(14) [Reset] #x302005C73FED>
   [Condition of type SIMPLE-ERROR]

**Comment by phoe** [comment]
Looks like scigraph makes the mistake where it thinks it is possible to read from stream objects created in different threads.

I cannot see scigraph on quicklisp. Where are the sources located?

**Comment by saufesma** [comment]
>I cannot see scigraph on quicklisp. Where are the sources located?

/quicklisp/dists/quicklisp/software/mcclim-20201016-git/Apps/Scigraph

>Looks like scigraph makes the mistake where it thinks it is possible to read from stream objects created in different threads.

Or ./lx86cl64 does not have a right to read?

**Comment by phoe** [comment]
I think it can read just fine - the error message stays that the stream object is private to one thread, but it seems that something attempts to read from that stream from another thread.

Can you provide a backtrace?

**Comment by saufesma** [comment]
Incorrect keyword arguments in ((LIST GRAPH)) .
   [Condition of type CCL::SIMPLE-PROGRAM-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT-BREAK] Reset this thread
 3: [ABORT] Kill this thread


Backtrace:
  0: (NIL #<Unknown Arguments>)
  1: (CCL::%TRACE-0 ((VIEW-GRAPHS (LIST GRAPH))) NIL)
  2: (CCL::CALL-CHECK-REGS CCL::%TRACE-0 ((VIEW-GRAPHS (LIST GRAPH))) NIL)
  3: (CCL::CHEAP-EVAL (TRACE (VIEW-GRAPHS (LIST GRAPH))))
  4: (SWANK::EVAL-REGION "(trace (view-graphs (list graph)))\n")
  5: ((:INTERNAL SWANK-REPL::REPL-EVAL))
  6: (SWANK-REPL::TRACK-PACKAGE #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL SWANK-REPL::REPL-EVAL) #x3020060352BF>)
  7: (SWANK::CALL-WITH-RETRY-RESTART "Retry SLIME REPL evaluation request." #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL SWANK-REPL::REPL-EVAL) #x30200603533F>)
  8: (SWANK::CALL-WITH-BUFFER-SYNTAX NIL #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL SWANK-REPL::REPL-EVAL) #x30200603537F>)
  9: (SWANK-REPL::REPL-EVAL "(trace (view-graphs (list graph)))\n")
 10: (CCL::CALL-CHECK-REGS SWANK-REPL:LISTENER-EVAL "(trace (view-graphs (list graph)))\n")
 11: (CCL::CHEAP-EVAL (SWANK-REPL:LISTENER-EVAL "(trace (view-graphs (list graph)))\n"))
 12: (SWANK:EVAL-FOR-EMACS (SWANK-REPL:LISTENER-EVAL "(trace (view-graphs (list graph)))\n") "GRAPH" 109)
 13: (SWANK::PROCESS-REQUESTS NIL)
 14: ((:INTERNAL SWANK::HANDLE-REQUESTS))
 15: ((:INTERNAL SWANK::HANDLE-REQUESTS))
 16: (SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK #<Compiled-function SWANK:SWANK-DEBUGGER-HOOK (Non-Global)  #x30200093209F> #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL SWANK::HANDLE-REQUESTS) #x302000A6776F>)
 17: (SWANK::CALL-WITH-BINDINGS ((*STANDARD-INPUT* . #<SWANK/GRAY::SLIME-INPUT-STREAM #x302000A6637D>)) #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL SWANK::HANDLE-REQUESTS) #x302000A6772F>)
 18: (SWANK::HANDLE-REQUESTS #<MULTITHREADED-CONNECTION #x302000943B9D> NIL)
 19: (CCL::RUN-PROCESS-INITIAL-FORM #<PROCESS repl-thread(12) [Active] #x302000A66F4D> (#<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::%PROCESS-RUN-FUNCTION) #x302000A66CDF>))
 20: ((:INTERNAL (CCL::%PROCESS-PRESET-INTERNAL (CCL:PROCESS))) #<PROCESS repl-thread(12) [Active] #x302000A66F4D> (#<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::%PROCESS-RUN-FUNCTION) #x302000A66CDF>))
 21: ((:INTERNAL CCL::THREAD-MAKE-STARTUP-FUNCTION))

**Comment by phoe** [comment]
Wait a second, that's a different error. It happened because you used CCL's `trace` incorrectly.

Can you try just `(view-graphs (list graph))` instead and give me the backtrace?

**Comment by saufesma** [comment]
>Can you try just (view-graphs (list graph)) instead and give me the backtrace?

Stream #<BASIC-FILE-BINARY-INPUT-STREAM ("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"/7 ISO-8859-1) #x302005C8D58D> is private to #<PROCESS Frame Top Level(14) [Reset] #x302005C73FED>
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [CLEAR-PANE-TRY-AGAIN] Clear the output history of the pane and reattempt forceful redisplay.
 1: [CLEAR-PANE] Clear the output history of the pane, but don't redisplay.
 2: [SKIP-REDISPLAY] Skip this redisplay.
 3: [ABORT] Return to application command loop.
 4: [SCIGRAPH-TOP-LEVEL] Abort to SCIGRAPH Top Level
 5: [ABORT-BREAK] Reset this thread
 --more--

Backtrace:
  0: (CCL::CHECK-IOBLOCK-OWNER #S(CCL::FILE-IOBLOCK :STREAM #<BASIC-FILE-BINARY-INPUT-STREAM ("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"/7 ISO-8859-1) #x302005C8D58D> :UNTYI-CHAR NIL ..))
  1: (#<CCL::STANDARD-KERNEL-METHOD CCL::STREAM-POSITION (CCL::BASIC-FILE-INPUT-STREAM)> #<BASIC-FILE-BINARY-INPUT-STREAM ("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"/7 ISO-8859-1) #x302005C8D58D..
  2: (#<STANDARD-METHOD ZPB-TTF::INITIALIZE-BOUNDING-BOX (ZPB-TTF::GLYPH)> #<GLYPH "five" U+0035>)
  3: (CCL::%%BEFORE-AND-AFTER-COMBINED-METHOD-DCODE (NIL #<STANDARD-METHOD ZPB-TTF:BOUNDING-BOX :BEFORE (ZPB-TTF::GLYPH)> . 17519667737476))
  4: (CCL::%%STANDARD-COMBINED-METHOD-DCODE ((#<STANDARD-METHOD ZPB-TTF:BOUNDING-BOX :BEFORE (ZPB-TTF::GLYPH)>) NIL #<CCL:STANDARD-READER-METHOD ZPB-TTF:BOUNDING-BOX (ZPB-TTF::GLYPH)>) 17519667737476)
  5: (NIL #<Unknown Arguments>)
  6: (MCCLIM-TRUETYPE::GLYPH-PIXARRAY #<CLX-TRUETYPE-FONT  size=14 ascent=13307/1024 descent=3381/1024 units->pixels=7/1024> #\5 #\Null #<STANDARD-IDENTITY-TRANSFORMATION #x3020015C2D4D>)
  7: (#<STANDARD-METHOD MCCLIM-TRUETYPE::FONT-GENERATE-GLYPH (MCCLIM-TRUETYPE::CLX-TRUETYPE-FONT T)> #<CLX-TRUETYPE-FONT  size=14 ascent=13307/1024 descent=3381/1024 units->pixels=7/1024> 53 #<STANDARD-IDE..
  8: (MCCLIM-TRUETYPE::FONT-GLYPH-INFO #<CLX-TRUETYPE-FONT  size=14 ascent=13307/1024 descent=3381/1024 units->pixels=7/1024> 53)
  9: (#<STANDARD-METHOD CLIM-BACKEND:FONT-GLYPH-LEFT (MCCLIM-TRUETYPE::CACHED-TRUETYPE-FONT T)> #<CLX-TRUETYPE-FONT  size=14 ascent=13307/1024 descent=3381/1024 units->pixels=7/1024> 53)
 10: (CLIM-INTERNALS::LINE-BBOX #<CLX-TRUETYPE-FONT  size=14 ascent=13307/1024 descent=3381/1024 units->pixels=7/1024> #(53) :LEFT)
 11: (#<STANDARD-METHOD CLIM-BACKEND:FONT-TEXT-EXTENTS (T T)> #<CLX-TRUETYPE-FONT  size=14 ascent=13307/1024 descent=3381/1024 units->pixels=7/1024> "5" :START 0 :END 1 :ALIGN-X :LEFT :ALIGN-Y :BASELINE :D..
 12: (CCL::%%CHECK-KEYWORDS #(2 #(:DIRECTION :ALIGN-Y :ALIGN-X :END :START) #<CCL:METHOD-FUNCTION CLIM-BACKEND:FONT-TEXT-EXTENTS (T T)>) 17519667737578)
 13: (NIL #<Unknown Arguments>)
 14: (#<STANDARD-METHOD CLIM-BACKEND:TEXT-BOUNDING-RECTANGLE* (CLIM-BACKEND:FONT-RENDERING-MEDIUM-MIXIN T)> #<CLIM-CLX:CLX-RENDER-MEDIUM #x302005B8D67D> "5" :TEXT-STYLE #<STANDARD-TEXT-STYLE :FIX :ROMAN :N..
 15: (CCL::%%CHECK-KEYWORDS #(2 #(:DIRECTION :ALIGN-Y :ALIGN-X :END :START :TEXT-STYLE) #<CCL:METHOD-FUNCTION CLIM-BACKEND:TEXT-BOUNDING-RECTANGLE* (CLIM-BACKEND:FONT-RENDERING-MEDIUM-MIXIN T)>) 1751966773..
 16: (NIL #<Unknown Arguments>)
 17: (#<STANDARD-METHOD INITIALIZE-INSTANCE :AFTER (CLIM-INTERNALS::DRAW-TEXT-OUTPUT-RECORD)> #<DRAW-TEXT-OUTPUT-RECORD X 0.0D0:0.0D0 Y 0.0D0:0.0D0>)
 18: (CCL::%%BEFORE-AND-AFTER-COMBINED-METHOD-DCODE (NIL #<STANDARD-METHOD INITIALIZE-INSTANCE :AFTER (CLIM-INTERNALS::DRAW-TEXT-OUTPUT-RECORD)> . 17519667737661))
 19: (CCL::%%STANDARD-COMBINED-METHOD-DCODE (NIL (#<STANDARD-METHOD INITIALIZE-INSTANCE :AFTER (STANDARD-RECTANGLE)> #<STANDARD-METHOD INITIALIZE-INSTANCE :AFTER #> #<#> #<#> #<#> #<#> ...) ..))) 175196677..
 20: (NIL #<Unknown Arguments>)
 21: (CCL::%MAKE-STD-INSTANCE #<STANDARD-CLASS CLIM-INTERNALS::DRAW-TEXT-OUTPUT-RECORD> (:STREAM #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED> :STRING "5" :POINT-X 547 ...))
 22: (#<CCL::STANDARD-KERNEL-METHOD MAKE-INSTANCE (STANDARD-CLASS)> #<STANDARD-CLASS CLIM-INTERNALS::DRAW-TEXT-OUTPUT-RECORD> :STREAM #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED> :STRING "5" :POINT..
 23: (CCL::%MAKE-INSTANCE #<CLASS-CELL for CLIM-INTERNALS::DRAW-TEXT-OUTPUT-RECORD #x302001936FCD> :STREAM #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED> :STRING "5" :POINT-X 547 :POINT-Y 304 :ALIGN-..
 24: (#<STANDARD-METHOD MEDIUM-DRAW-TEXT* :AROUND (OUTPUT-RECORDING-STREAM T T T T T ...)> #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED> "5" 547 304 0 NIL :LEFT :BASELINE 548 304 NIL)
 25: (CCL::%%STANDARD-COMBINED-METHOD-DCODE (#<STANDARD-METHOD MEDIUM-DRAW-TEXT* :AROUND (OUTPUT-RECORDING-STREAM T T T T T ...)> #<STANDARD-METHOD MEDIUM-DRAW-TEXT* (CLIM:SHEET T T T T T ...)>) 1751966773..
 26: (NIL #<Unknown Arguments>)
 27: (#<STANDARD-METHOD CLIM-INTERNALS::DO-GRAPHICS-WITH-OPTIONS-INTERNAL (MEDIUM T T)> #<CLIM-CLX:CLX-RENDER-MEDIUM #x302005B8D67D> #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED> #<CCL:COMPILED-LEXI..
 28: ((:INTERNAL #:G58345 (CLIM-INTERNALS::DO-GRAPHICS-WITH-OPTIONS (CLIM:SHEET T))) #<CLIM-CLX:CLX-RENDER-MEDIUM #x302005B8D67D>)
 29: (DRAW-TEXT* #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED> "5" 547 304 :INK #<CLIM-INTERNALS::%FOREGROUND-INK #x3020017899BD> :ALIGN-X :LEFT :ALIGN-Y :BASELINE :TEXT-STYLE NIL :TRANSFORM-GLYPHS ..
 30: (LINEAR-AXIS 80 54 573 54 -0.25 5.25 1.0 7 :MINIMAL #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL (DISPLAY-BORDER (GRAPH-BORDER-MIXIN T))) #x30200605EF8F> #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL ..) NIL..
 31: ((:INTERNAL (DISPLAY-BORDER (GRAPH-BORDER-MIXIN T))))
 32: (#<STANDARD-METHOD GRAPH-WITH-CLIPPING (BASIC-GRAPH T T T)> #<ANNOTATED-GRAPH ANNOTATED-GRAPH-3> #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED> NIL #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL ..))
 33: (#<STANDARD-METHOD DISPLAY :AFTER (GRAPH-BORDER-MIXIN T)> #<ANNOTATED-GRAPH ANNOTATED-GRAPH-3> #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED>)
 34: (CCL::%%BEFORE-AND-AFTER-COMBINED-METHOD-DCODE (#(#<STANDARD-GENERIC-FUNCTION DISPLAY #x3020057FF2AF> (#<#> #<#> #<#> #<#> #<#> #<#> ...) NIL NIL (#<#> # # #<#>)) ..)))
 35: (CCL::%%CNM-WITH-ARGS-COMBINED-METHOD-DCODE #(#<STANDARD-GENERIC-FUNCTION DISPLAY #x3020057FF2AF> (#<STANDARD-METHOD DISPLAY :AFTER #> #<#> #<#> #<#> #<#> #<#> ...) NIL NIL ..) (#<ANNOTATED-GRAPH ANNO..
 36: (CCL::%CALL-NEXT-METHOD-WITH-ARGS ((#(#<STANDARD-GENERIC-FUNCTION DISPLAY #x3020057FF2AF> # NIL NIL #)) ..))) #<ANNOTATED-GRAPH ANNOTATED-GRAPH-3> #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED>)
 37: ((:INTERNAL #:CONTINUATION17877 #:UPDATING-OUTPUT-CONTINUATION17868 (DISPLAY :AROUND (PRESENTABLE-GRAPH-MIXIN T))) #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED> #<STANDARD-PRESENTATION 61:1147/..
 38: (#<STANDARD-METHOD INVOKE-WITH-NEW-OUTPUT-RECORD (OUTPUT-RECORDING-STREAM T T)> #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED> #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL ..) STANDARD-PRESENTATION..
 39: ((:INTERNAL #:UPDATING-OUTPUT-CONTINUATION17868 (DISPLAY :AROUND (PRESENTABLE-GRAPH-MIXIN T))) #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED>)
 40: (#<STANDARD-METHOD INVOKE-WITH-NEW-OUTPUT-RECORD (OUTPUT-RECORDING-STREAM T T)> #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED> #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL ..) STANDARD-SEQUENCE-OUT..
 41: (CLIM-INTERNALS::%INVOKE-UPDATING #<STANDARD-UPDATING-OUTPUT-RECORD X 0.0D0:0.0D0 Y 0.0D0:0.0D0  #<ANNOTATED-GRAPH ANNOTATED-GRAPH-3> #x30200605F4BD> #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEE..
 42: ((:INTERNAL #:CONTINUATION91508 (INVOKE-UPDATING-OUTPUT (CLIM-INTERNALS::UPDATING-OUTPUT-STREAM-MIXIN T T T T T ...))) #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED> #<STANDARD-UPDATING-OUTPUT-R..
 43: (#<STANDARD-METHOD INVOKE-WITH-NEW-OUTPUT-RECORD (OUTPUT-RECORDING-STREAM T T)> #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED> #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL ..) STANDARD-UPDATING-OUT..
 44: (#<STANDARD-METHOD INVOKE-UPDATING-OUTPUT (CLIM-INTERNALS::UPDATING-OUTPUT-STREAM-MIXIN T T T T T ...)> #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED> #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL ...
 45: (CCL::%%CHECK-KEYWORDS #(7 #(:PARENT-CACHE :ALL-NEW :FIXED-POSITION) #<CCL:METHOD-FUNCTION INVOKE-UPDATING-OUTPUT (CLIM-INTERNALS::UPDATING-OUTPUT-STREAM-MIXIN T T T T T ...)>) 17519667738074)
 46: (NIL #<Unknown Arguments>)
 47: (#<STANDARD-METHOD DISPLAY :AROUND (PRESENTABLE-GRAPH-MIXIN T)> #<ANNOTATED-GRAPH ANNOTATED-GRAPH-3> #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED>)
 48: (CCL::%%CNM-WITH-ARGS-COMBINED-METHOD-DCODE #(#<STANDARD-GENERIC-FUNCTION DISPLAY #x3020057FF2AF> (#<STANDARD-METHOD DISPLAY :AFTER #> #<#> #<#> #<#> #<#> #<#> ...) NIL NIL ..) 17519667738118 NIL)
 49: (NIL #<Unknown Arguments>)
 50: (DISPLAY-GRAPH #<ANNOTATED-GRAPH ANNOTATED-GRAPH-3> :STREAM #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED> :SCROLL-IF-NECESSARY NIL :WIDTH 581 :HEIGHT 340)
 51: (DISPLAY-GRAPHS (#<ANNOTATED-GRAPH ANNOTATED-GRAPH-3>) :STREAM #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED> :WIDTH 581 :HEIGHT 10893/32)
 52: (FILL-WINDOW-WITH-GRAPHS (#<ANNOTATED-GRAPH ANNOTATED-GRAPH-3>) :AUTOSCALE NIL :RIGHT-MARGIN 0 :COLUMNS 1 :STREAM #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED> :REVERSE-VIDEO :OWN-COLOR)
 53: (CLIM-INTERNALS::INVOKE-DISPLAY-FUNCTION #<GRAPH-VIEWER #x302005B72C2D> #<CLX-10068-APPLICATION-PANE DISPLAY #x302005B8EEED>)
 54: (CCL::%CALL-NEXT-METHOD ((#(#<STANDARD-GENERIC-FUNCTION REDISPLAY-FRAME-PANE #x3020015361CF> # # # #)) ..)))
 55: (CCL::%%BEFORE-AND-AFTER-COMBINED-METHOD-DCODE ((#(#<STANDARD-GENERIC-FUNCTION REDISPLAY-FRAME-PANE #x3020015361CF> # # # #)) ..)))
 56: (CCL::%CALL-NEXT-METHOD ((#(#<STANDARD-GENERIC-FUNCTION REDISPLAY-FRAME-PANE #x3020015361CF> # # # #)) ..)))
 57: (#<STANDARD-METHOD REDISPLAY-FRAME-PANE :AROUND (APPLICATION-FRAME T)> ((#(#<STANDARD-GENERIC-FUNCTION REDISPLAY-FRAME-PANE #x3020015361CF> # # # #)) ..)) #<GRAPH-VIEWER #x302005B72C2D> :FORCE-P #<CLX..
 58: (CCL::%%CNM-WITH-ARGS-COMBINED-METHOD-DCODE #(#<STANDARD-GENERIC-FUNCTION REDISPLAY-FRAME-PANE #x3020015361CF> (#<STANDARD-METHOD REDISPLAY-FRAME-PANE :AFTER #> #<#> #<#> #<#> #<#>) ..))) 175196677382..
 59: (NIL #<Unknown Arguments>)
 --more--

**Comment by phoe** [comment]
Yep, that is what happens. I've let `#clim` on Libera Chat know about this issue as I do not think this is a problem with CCL itself - it is a problem with using it in an incorrect way. See https://ccl.clozure.com/docs/ccl.html#stream-extensions and the custom `:sharing` keyword available for the `open` function.

**Comment by saufesma** [comment]
>See https://ccl.clozure.com/docs/ccl.html#stream-extensions and the custom :sharing keyword available for the open function.

Well, I am humble user.

**Comment by phoe** [comment]
Yep. That's why I've notified `#clim` - quite possibly the issue needs to get fixed on the CLIM side. Could you make a ticket on https://github.com/McCLIM/McCLIM/ ?

**Comment by nsrahmad** [comment]
@saufesma  The problem was in `zpb-ttf` system. It is a single line change so you could edit the file yourself and see if it fixes it.
