### ISSUE TITLE
Download page says latest release is 1.12 and points to its github page, but it should say 1.12.1 and point there

### ISSUE THREAD

**Issue by KalmanReti** [Clozure/ccl#385]
Also, the windows ccl .zip file has a problem when extracting. 7-zip says it can't open 79 files (mostly documentation and header files, the 7-zip error dialog won't let me copy the list).  The prior (1.12, not 1.12.1) zip file didn't have this problem, so I expect dropping in the files from it would be a suitable workaround.  Looking at the same .zip file with emacs generated an error about matching filename not found, where the displayed filename ended in a ^M (crtl-m, i.e. carriage return).

**Comment by avodonosov** [comment]
The Download page still mentions 1.12. 

Is the 1.12.1 the recommended release, or we should still use 1.12?

**Comment by xrme** [comment]
I think the issue with funny zip files is fixed with the 1.12.2 release.

The download page on ccl.clozure.com also refers to 1.12.2 now.
