### ISSUE TITLE
Incorrect printing of floating-point number

### ISSUE THREAD

**Issue by rtoy** [Clozure/ccl#394]
I'm using ccl 1.12 LinuxX8664.

```
? (format t "~,v,,ve" 15 2 1d10)
10.00000000000000D+8
```
The printed result is off by a factor of 10; the exponent should be 9, not 8.

Presumably there's a round-off problem in figuring out the exponent to print.

This is a serious problem in printing that I found with maxima's engineering format that uses the scale factor parameter for `~e` to print floating point number in the form x*10^n where n is a multiple of 3.

**Comment by LdBeth** [comment]
I investigated it a little and find that
```
(format t "~,3,,0e" 11)
```
signals an error
```
The value NIL is not of the expected type REAL.
   [Condition of type TYPE-ERROR]

Backtrace:
 0: (CCL::<-2 NIL 0)
 1: (CCL::>=-2 NIL 0)
 2: (CCL::FORMAT-EXP-AUX #<SLYNK-GRAY::SLY-OUTPUT-STREAM #x302000B1475D> 11.0 NIL 3 NIL 0 NIL #\  NIL NIL "11" 3)
```
and on SBCL or ECL both gives `0.110e+2`.

**Comment by LdBeth** [comment]
And I found one more bug:

```
? (format t "~10,5,,-2e" .00123445)
0.00120E+0
NIL
? (format t "~10,5,,-3e" .00123445)
0.00010E+1
NIL
```

**Comment by LdBeth** [comment]
There is one more "bug" I found:
```
(format t "~9,3,2,-2e" 1100.0) ;; Should be "0.001E+06"
```

After I fixed that seems the only problems are when the number is `0`:
```
> (format t "~10,5,,2e" 0.0)
00.0000E-2
```

```
> (format t "~10,,,-2e" 0.01)
  0.001E+1
```
while SBCL gives `   0.0e+5` here,
I think this is acceptable since the CL specification seems did not mention what to do in this case.
