### ISSUE TITLE
Clozure CL crash on startup - MacOS 12.1

### ISSUE THREAD

**Issue by zslg01** [Clozure/ccl#401]
Get a crash on launch of current clozure cl on MacOS 12.1

> Error: Objective-C runtime exception: 
>        -[HemlockBufferString count]: unrecognized selector sent to instance 0x60000000af10
> While executing: #<Anonymous Function #x30000111176F>, in process Initial(0).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
1 >

**Comment by dwsinger** [comment]
I'd love to get Clozure working again.

**Comment by dwsinger** [comment]
@mdbergmann what versions of OS and Clozure have you got running?

**Comment by mdbergmann** [comment]
I currently run macOS 12.3 and CCL 

```
❯ ccl --version
Version 1.12.1  DarwinX8664
```

But things also worked with earlier versions of CCL.
Using CCL from Homebrew.

**Comment by asmaloney** [comment]
FWIW I have just tried the binaries from the [1.12.1 release](https://github.com/Clozure/ccl/releases/tag/v1.12.1) on both macOS **10.14.6** (Intel) and macOS **12.4** (Intel).

The command line (`./dx86cl64 --version`) seems to be working for me on both.

**Comment by xrme** [comment]
If you're trying to use the Mac App Store version of CCL, it's broken.

If you get the current release and build your own IDE with `(require 'cocoa-application)` then you should get an app that works.

**Comment by dwsinger** [comment]
a new version for the app store is not planned?

**Comment by xrme** [comment]
I'd love to have it back in the app store, but I don't have a plan for when.

The main problem is that an IDE only runs on the version of the operating system it is compiled on.  In other words, an IDE build on (for example) Big Sur will run on Big Sur, but not on Monterey or anything later.  I don't yet understand why this is the case.

See #272.
