### ISSUE TITLE
Very confusing build/usage instructions for Windows

### ISSUE THREAD

**Issue by aks2161989** [Clozure/ccl#402]
First, is building CCL even necessary on Windows or can I just use the ccl-1.12-windowsx86.zip distribution? What do I miss out by not building it myself?

The releases page does not make it clear if you need to build CCL on Windows or can just download and use the binaries

On the releases page, the build instructions for Windows are very vague. It is not clear if the author is talking about the ccl-dev repository or the binary distribution when using he cd command. Both the binaries folder and the ccl-dev have the lisp-kernel folder, so that makes it even more confusing.

**Comment by aks2161989** [comment]
When running 'make' in ccl-dev/lisp-kernel/win64 i get the following error message

```
/usr/bin/sh: x86_64-w64-mingw32-ld: command not found
m4 -DWIN_64 -DWINDOWS -DX86 -DX8664 -DHAVE_TLS -DEMUTLS -DTCR_IN_GPR -I../ ../pad.s | x86_64-w64-mingw32-as  -g --64 -o
pad.o
/usr/bin/sh: m4: command not found
/usr/bin/sh: x86_64-w64-mingw32-as: command not found
make: *** [Makefile:95: pad.o] Error 127
```

**Comment by em7** [comment]
It looks like you don't have the GNU toolchain properly installed. For me the easiest way always was to use MSYS2 distribution, please follow instructions on https://www.msys2.org/ . When the toolchain is installed, run "MSYS MinGW 64-bit" from Start menu. It compiled.
Question is WHY you want to compile it on your own. I don't think that it would give you any benefit.

**Comment by xrme** [comment]
As of the 1.12.2 release, the makefiles in `lisp-kernel/win32` and `lisp-kernel/win64` contain comments with instructions on how to use the MSYS2 build platform to compile the lisp kernel for Windows.

It's not necessary to compile the lisp kernel if you just want to run the release. https://github.com/Clozure/ccl/releases/download/v1.12.2/ccl-1.12.2-windowsx86.zip contains pre-complied binaries.
