### ISSUE TITLE
Conflicting with proxychains

### ISSUE THREAD

**Issue by glyh** [Clozure/ccl#403]
When proxychains is present, ccl will terminate with:
```
[proxychains] DLL init: proxychains-ng 4.15
fish: Job 1, 'ccl' terminated by signal SIGABRT (Abort)
```
Here's a video demonstrate how to reproduce this, `a` is alias to `paru`, which is my AUR helper in Arch Linux for installing packages:

[![asciicast](https://asciinema.org/a/jHR3mPgg0KaheWgoKLOpJ0Y9F.svg)](https://asciinema.org/a/jHR3mPgg0KaheWgoKLOpJ0Y9F)

**Comment by xrme** [comment]
I don't really know what proxychains does, but from a quick search, it looks like it tries to perform dynamic linker tricks.

CCL uses dlopen/dlsym frequently, and according to the README of https://github.com/rofl0r/proxychains-ng this might cause proxychains not to work.

I don't believe this is a CCL bug.
