### ISSUE TITLE
Dumped lisp images on Linux hang on program termination starting with glibc-2.33-108-g3e2a15c666

### ISSUE THREAD

**Issue by sternenseemann** [Clozure/ccl#405]
Yesterday I started to run into the issue that, after updating [nixpkgs](https://github.com/nixos/nixpkgs), all dumped images by ccl would  crash with the following error message and hang forever.

```
$ ./result/bin/argv0-test
./result/bin/argv0-test

Unhandled error: Fault during read of memory address #x7FFFD7BA95A8
> Error: Fault during read of memory address #x7FFFD7BA95A8
> While executing: CCL::LISP-THREAD-SUSPEND-COUNT, in process Initial(0).


;;;
;;; #<PROCESS Initial(0) [Active] #x3020000BA59D> requires access to Shared Terminal Input
;;; Type (:y 0) to yield control to this thread.
;;;
```

The source for this program is:

```lisp
(defpackage :argv0-test (:use :common-lisp :uiop) (:export :main))
(in-package :argv0-test)

(defun main ()
  (format t "~A~%" (uiop:argv0)))
```

Interestingly it executes normally before the crash which seems to happen in some kind of CCL shutdown function (this is also true for other programs as far as I can tell).

I started to bisect nixpkgs and arrived at <https://github.com/nixos/nixpkgs/commit/512ba72a55113d67815fb1525089c5959b3a3a98>, a glibc patch-level (!) update. Since all patches in that range either didn't tell me anything or seemed innocent enough, I started bisecting glibc itself, arriving at [3e2a15c666e40e5ee740e5079c56d83469280323](https://sourceware.org/git/?p=glibc.git;a=commit;h=3e2a15c666e40e5ee740e5079c56d83469280323) as the first bad commit.

Due to my lack of knowledge of CCL internals, I don't know what to make of this, unfortunately.

**Comment by phoe** [comment]
CCL seems to be hanging in the debugger. Type `(:y 0)` to gain control of it, then `:b` to produce the backtrace.

**Comment by sternenseemann** [comment]
Any input is ignored (maybe it has closed stdin already), so that's not possible unfortunately.

**Comment by phoe** [comment]
OK, weird. What is your CCL version?

**Comment by sternenseemann** [comment]
nixpkgs provides CCL 1.12 at the moment, I can offer to try from master or 1.12.1, depending on what you prefer.

**Comment by phoe** [comment]
I'm digging in the source code. Seems that `LISP-THREAD-SUSPEND-COUNT` is here:

https://github.com/Clozure/ccl/blob/6c1a9458f7a5437b73ec227e989aa5b825f32fd3/level-1/l1-lisp-threads.lisp#L513-L525

And it is only called in one place, in `PROCESS-SUSPEND-COUNT`:

https://github.com/Clozure/ccl/blob/6c1a9458f7a5437b73ec227e989aa5b825f32fd3/level-1/l1-processes.lisp#L325-L331

Which itself seems to be called from `PROCESS-ACTIVE-P`:

https://github.com/Clozure/ccl/blob/6c1a9458f7a5437b73ec227e989aa5b825f32fd3/level-1/l1-processes.lisp#L333-L336

Which, indeed, is called as a part of `PREPARE-TO-QUIT`:

https://github.com/Clozure/ccl/blob/6c1a9458f7a5437b73ec227e989aa5b825f32fd3/level-1/l1-readloop.lisp#L139-L176

**Comment by phoe** [comment]
> nixpkgs provides CCL 1.12 at the moment, I can offer to try from master or 1.12.1, depending on what you prefer.

That's relatively fresh.

The root cause I see at the moment is that `LISP-THREAD-SUSPEND-COUNT` seems to read some memory here:

https://github.com/Clozure/ccl/blob/6c1a9458f7a5437b73ec227e989aa5b825f32fd3/level-1/l1-lisp-threads.lisp#L523-L525

And that causes a segmentation violation. Why, though? And why would a glibc patch expose such an issue? I am not competent enough to work with CCL TCRs in order to debug this.

**Comment by sternenseemann** [comment]
This issue has inexplicably fixed itself. I've tried bisecting it a bit, but just ended up at some random merge commit so far. Version changes among CCL's dependency closure also don't look terribly related:

```
<<< /nix/store/d1rfxfz176rldhc5xrjdxm73nf4q5n82-ccl-1.12.drv
>>> /nix/store/xnfp0494givp2akxalkd15dq38bsqh7y-ccl-1.12.drv
Version changes:
[U.]  #1  Python              3.9.9.tar.xz -> 3.9.10.tar.xz
[U.]  #2  expat               2.4.2, 2.4.2.tar.xz -> 2.4.4, 2.4.4.tar.xz
[U.]  #3  krb5                1.18.tar.gz -> 1.19.2.tar.gz
[U.]  #4  libkrb5             1.18 -> 1.19.2
[U.]  #5  linux               5.15.5.tar.xz -> 5.16.tar.xz
[U.]  #6  linux-headers       5.15.5 -> 5.16
[C.]  #7  pkg-config          0.29.2, 0.29.2.tar.gz -> 0.29.2 x2, 0.29.2.tar.gz
[C.]  #8  pkg-config-wrapper  0.29.2 -> 0.29.2 x2
[U.]  #9  python3-minimal     3.9.9 -> 3.9.10
Added packages:
[A.]  #1  0001-Remove-unused-function-after_eq.patch  <none>
[A.]  #2  autoconf-archive                            2021.02.19, 2021.02.19.tar.xz
Closure size: 281 -> 286 (122 paths added, 117 paths removed, delta +5).
```

Crucially, glibc hasn't been touched since I've experienced the issue.

**Comment by phoe** [comment]
That's both relieving and concerning. Should we keep this issue open?

**Comment by sternenseemann** [comment]
I don't think I'll investigate this further, so probably not much use in keeping this open? Either is fine with me.

**Comment by sternenseemann** [comment]
We managed to trigger this again, this time by rebuilding everything up to ccl with zlib 1.2.12 instead of 1.2.11. As far as I can tell the only packages we depend on for building ccl on that directly depend on zlib are:

* GNU binutils
* gcc
* bash (which just executes build scripts)
* python (probably some build script or documentation generation somewhere, not sure)

**Comment by sternenseemann** [comment]
I ran diffoscope over

* [ccl itself](https://sterni.lv/tmp/ccl-diff/ccl-diff/)
* [the dumped images](https://sterni.lv/tmp/ccl-diff/image-diff)

In case that may help.

**Comment by sternenseemann** [comment]
This issue has now mysteriously appeared on three occasions and fixed itself mysteriously two times. Every time it coincides with an update of dependencies (glibc once, zlib once, ?? third time), not sure what caused the situation resolving itself exactly.
