### ISSUE TITLE
Can't build v1.12.1 on win64

### ISSUE THREAD

**Issue by ro6** [Clozure/ccl#408]
```
/mingw64/bin/x86_64-w64-mingw32-gcc -include ../platform-win64.h -c ../pmcl-kernel.c -DWIN_64 -DWINDOWS -D_REENTRANT -DX86 -DX8664 -D_GNU_SOURCE -DHAVE_TLS -DEMUTLS -DTCR_IN_GPR -DVC_REVISION="unknown" -g -O2 -Wno-format  -m64 -o pmcl-kernel.o
make: *** [Makefile:97: pmcl-kernel.o] Error 1
```
seems to be the relevant failure. Pretty nondescript "Error 1" and `make -d` wasn't much better.

This is on `msys2 20220128.0.0` installed with Choco.

![image](https://user-images.githubusercontent.com/8773802/159215783-dee427d7-9e59-4527-a3c2-ada71f0bc8ef.png)

**Comment by xrme** [comment]
Let's use #425 for the Windows build problems.
