### ISSUE TITLE
Less favorable performance compared to SBCL in a simple case

### ISSUE THREAD

**Issue by GongYiLiao** [Clozure/ccl#41]
The following example:

```
;; 
(defun randu (n) (loop :repeat n :collect (random 1.0)))

;; 
(defun mean (x) (/ (loop for i in x sum i) (length x)))

;;
(defun moment (x p) (/ (loop for i in x sum (expt i p)) (length x)))

;; 
(defun var (x) (- (moment x 2) (expt (mean x) 2)))
```

On a netbook with Intel(R) Atom(TM) CPU N455   @ 1.66GHz, CCL took 4.5 seconds to run `(var (randu 1e6))` while SBCL only took 0.8 seconds (in both case the source code file is compiled then the .fasl or .lx86fsl files are loaded).

I am wondering if this is due to I didn't use CCL properly, any comments are appreciated.

**Comment by xrme** [comment]
You might want to post this question to openmcl-devel@clozure.com.  It seems like the mailing list would be a better place, but maybe I am wrong about that.

**Comment by SFurnace** [comment]
Recently I am finding a proper CL Implementation for study, so I have compared some CL Implementations. 
There's no doubt SBCL do better in number calculations, If you really care about it, you should use SBCL.
But with your example, when I eval `(var (randu 1e8))` in Slime using SBCL, it just output nothing. And in \*inferior-lisp\* buffer it shows **"Heap exhausted, game over"**. I have to change the default heap size by hand to make things right. That won't happen in CCL.
