### ISSUE TITLE
Downloading CCL 1.7 or 1.8

### ISSUE THREAD

**Issue by stew-j** [Clozure/ccl#420]
Does anyone know where and how to download binaries for either of these?  See this for the details of my problem:

https://github.com/kaveh808/kons-9/issues/4

**Comment by mdbergmann** [comment]
I got them from here: 
https://ccl.clozure.com/ftp/pub/release/1.7/

**Comment by stew-j** [comment]
Thanks!

**Comment by stew-j** [comment]
Regression :(
