### ISSUE TITLE
[intentional] Array size is limited to (EXPT 2 24) on ARM32.

### ISSUE THREAD

**Issue by zinadv** [Clozure/ccl#429]
Why array size (on ARM32) is limited to (EXPT 2 24)? I need more: CCL is do-all on my ARM :)

```
(fixnump (expt 2 28)) ;; => T
```

First thought was absurd: that ARM has some 24-bit immediate LDR instruction. But this is not immediate offset in general.

```
(progn
  (declare (speed 0) (safety 3))
  (let (a)
    (setf a (make-array 16777216
			:element-type 'single-float))
    (setf (aref a 16777215) 1.0)
    (aref a 16777215)))
;; =>
;; Array index 16777215 out of bounds for #() .
;; [Condition of type SIMPLE-ERROR]
```

Looks like some LOGAND on size at allocation.

```
(array-dimension (make-array 16777216
  :element-type '(unsigned-byte 8)) 0) ;; => 0

(array-dimension (make-array 16777217
  :element-type '(unsigned-byte 8)) 0) ;; => 1
```

So I can use 16x4 megabytes. 

```
(integer-length (aref (make-array 16777215
  :element-type '(unsigned-byte 64)
  :initial-element (ash 1 127)) 16777214)) ;; => 128
```

Looking at (DEFARM2 ARM2-%ALLOC-MISC %MAKE-UVECTOR ...)

Header? Was it intended limitation?
```
(ccl::element-type-subtype '(unsigned-byte 8)) ;; => 199
(ccl::element-type-subtype '(unsigned-byte 32)) ;; => 167
(integer-length (Arch::make-vheader 16777216 199)) ;; => 33
(integer-length (Arch::make-vheader 16777216 167)) ;; => 33
```

**Comment by informatimago** [comment]
Le 18/12/2022 à 19:05, zinadv a écrit :
> Why array size (on ARM32) is limited to (EXPT 2 24)? I need more: CCL is 
> do-all on my ARM :)

You may implement a bigarray data type:



(defpackage "BIGARRAY"
   (:use "COMMON-LISP")
   (:shadow "MAKE-ARRAY" "AREF" "LENGTH"
            #+test "ARRAY-TOTAL-SIZE-LIMIT")
   (:export "MAKE-ARRAY" "AREF" "LENGTH"
            #+test "ARRAY-TOTAL-SIZE-LIMIT"))

(defpackage "CL-WITH-BIGARRAY"
   (:use "COMMON-LISP" "BIGARRAY")
   (:shadowing-import-from "BIGARRAY"
                           "MAKE-ARRAY" "AREF" "LENGTH"
                           #+test "ARRAY-TOTAL-SIZE-LIMIT")
   (:export . #.(let ((e '()))
                  (do-external-symbols (s "COMMON-LISP" e)
                    (push (symbol-name s) e)))))

(in-package "BIGARRAY")

#+test (defconstant ARRAY-TOTAL-SIZE-LIMIT 8)

(defstruct bigvector
   total-size
   slice-size
   last-slice-size
   slices)

(defun allocate-vector (size element-type #|fill-pointer etc|#)
   (multiple-value-bind (nslices last-slice-size)
       (truncate size array-total-size-limit)
     (if (plusp last-slice-size)
         (incf nslices)
         (setf last-slice-size array-total-size-limit))
     (let ((v (make-bigvector :total-size size
                              :slice-size array-total-size-limit
                              :last-slice-size last-slice-size
                              :slices (make-array nslices))))
       ;; (bigvector-slices v) could be a bigvector too!
       (dotimes (i nslices)
         (setf (aref (bigvector-slices v) i)
               (cl:make-array (if (= i (1- nslices))
                                  last-slice-size
                                  array-total-size-limit)
                              :element-type element-type
                              #|etc|#)))
       v)))

(defmethod make-array ((size integer) &rest parameters &key 
(element-type t) &allow-other-keys)
   (if (< size array-total-size-limit)
       (apply (function cl:make-array) size parameters)
       (allocate-vector size element-type)))

(defmethod make-array ((size list)  &rest parameters &key &allow-other-keys)

   ;; For multi-dimensionnal arrays you have the opportunity to
   ;; optimize the mapping of the planes into slices.

   ;; For example, by processing (reverse size) and taking dimensions
   ;; while their product is less than array-total-size-limit, we can
   ;; use a CL multi-dimensionnal array for a slice, and going on with
   ;; the remaining dimensions for the meta-slices and
   ;; meta-meta-slices, etc.  So the slices could be smaller than
   ;; array-total-size-limit, but that would allow us to process the
   ;; multidimension array efficiently.

   (not-implemented-yet))


;; Forward to CL classes:

(defmethod aref ((a array) &rest indices)
   (apply (function cl:aref) a indices))

(defmethod (setf aref) (new-value (a array) &rest indices)
   (setf (apply (function cl:aref) a indices) new-value))

(defmethod length ((v sequence))
   (cl:length v))

;; New methods for our classes:

(defmethod aref ((v bigvector) &rest indices)
   (assert (= 1 (length indices)))
   (multiple-value-bind (slice index) (truncate (first indices) 
array-total-size-limit)
     ;; Notice the recursive call to aref:
     (cl:aref (aref (bigvector-slices v) slice) index)))

(defmethod (setf aref) (new-value (v bigvector) &rest indices)
   (assert (= 1 (length indices)))
   (multiple-value-bind (slice index) (truncate (first indices) 
array-total-size-limit)
     ;; Notice the recursive call to aref:
     (setf (cl:aref (aref (bigvector-slices v) slice) index) new-value)))

(defmethod length ((v bigvector))
   (bigvector-total-size v))


(defpackage "MY-PROGRAM"
   (:use "CL-WITH-BIGARRAY"))
(in-package "MY-PROGRAM")

(pprint (make-array (+ 4 (expt 8 3))))
;; #S(bigvector :total-size 516 :slice-size 8 :last-slice-size 4
;;              :slices #S(bigvector :total-size 65 :slice-size 8 
:last-slice-size 1
;;                                   :slices #S(bigvector :total-size 9 
:slice-size 8 :last-slice-size 1
;;                                                        :slices 
#(#(#(#(0 0 0 0 0 0 0 0) #(0 0 0 0 0 0 0 0)
;; 
#(0 0 0 0 0 0 0 0) #(0 0 0 0 0 0 0 0)
;;
...
;; 
#(0 0 0 0 0 0 0 0) #(0 0 0 0 0 0 0 0)))
;; 
#(#(#(0 0 0 0)))))))

(let ((v (make-array (+ 4 (expt 8 3)))))
   (loop :for i :below (+ 4 (expt 8 3))
         :do (setf (aref v i) i))
   (loop :for i :below (+ 4 (expt 8 3))
         :by 10
         :do (prin1 (aref v i)) (princ " "))
   (terpri)
   (pprint v)
   (values))

;; 0 10 20 30 40 50 60 70 80 90 100 110 120 130 140 150 160 170 180 190 
200 210 220 230 240 250 260 270 280 290 300 310 320 330 340 350 360 370 
380 390 400 410 420 430 440 450 460 470 480 490 500 510
;;
;; #S(bigvector :total-size 516 :slice-size 8 :last-slice-size 4
;;              :slices #S(bigvector :total-size 65 :slice-size 8 
:last-slice-size 1
;;                                   :slices #S(bigvector :total-size 9 
:slice-size 8 :last-slice-size 1
;;                                                        :slices 
#(#(#(#(0 1 2 3 4 5 6 7) #(8 9 10 11 12 13 14 15)
;; 
#(16 17 18 19 20 21 22 23)
;;
...
;; 
#(504 505 506 507 508 509 510 511)))
;; 
#(#(#(512 513 514 515)))))))



-- 
__Pascal Bourguignon__

**Comment by zinadv** [comment]
Thank you for showing me how to avoid redefining CL functions. Didn't know about CL:ARRAY-TOTAL-SIZE-LIMIT.

> The _upper **exclusive**_ bound on the array total size of an array.

> A positive fixnum, the exact magnitude of which is implementation-dependent, but which is _not less than **1024**_.

It's not a bug at all.

M_MMAP_THRESHOLD (man mallopt) is 512k. So chunk size should be between 512k and 8M (to reduce fragmentation). 

It is possible, however, to redefine AREF and MAKE-ARRAY closer to fixnum limit somewhere in .ccl-init.lisp :)


```
(setf *warn-if-redefine-kernel* nil)
```

**Comment by zinadv** [comment]
This is completely understandable desire to use one word (without almost empty second word with possible 5 bits of residue) in header for any kind of objects (including smallest ones). This, maybe, is what leads to small image size.

It looks like %ALLOC-MISC is used everywhere. 

%ALLOC-MISC used within MAKE-UARRAY-1 (level1/l1-utils@1042).

And within %ALLOC-MISC header is loads into 32-bit immediate (compiler/ARM/arm2@7584), so size is truncated to 24 bits without warning.

At least, it would like to warn (but don't silently truncate), when size is more than ARRAY-TOTAL-SIZE-LIMIT.

**Comment by zinadv** [comment]
It is possible to happen upon type checking with constant size.

```
(write (type-of (make-array 16777216 :element-type '(unsigned-byte 8))))
;; => BIG-ARRAY:BIG-ARRAY
```

> Compiler warnings
>    In an anonymous lambda form at position 3877:
>  Invalid type specifier (SIMPLE-ARRAY (UNSIGNED-BYTE 8) (16777216)):
>  Bad dimension in array type: 16777216.

I tried, and it is bad idea to redefine kernel functions in .ccl-init.lisp, because former functions appears out of nowhere.

Inside LET, former kernel functions used, even in REPL. And silently truncates.
```
(write (let (a)
  (type-of (make-array (ash 1 24) :element-type '(unsigned-byte 8))))) 
;; => (SIMPLE-ARRAY (UNSIGNED-BYTE 8) (0))
```

**Comment by xrme** [comment]
The sometimes-limiting value of (expt 2 24) for array-total-size-limit is baked into the implementation at a fairly low level, as you discovered by reading the sources.

All memory-allocated objects that are not cons cells are things called uvectors. A uvector has a header word that is the size of a machine word (32 bits on ARM). The lower 8 bits of the header word are called the subtag, and the upper 24 bits represent the element count.

It's easy to imagine alternative data representations, but changing CCL to use a different one would be a big job.
