### ISSUE TITLE
CCL.BUG\#1068.A fails on Windows 10

### ISSUE THREAD

**Issue by kyanha** [Clozure/ccl#433]
Test CL-TEST::CCL.BUG\#1068.A failed
Form: (LET* ((CL-TEST::NAME "a\\*x") (CL-TEST::NAME/ "a\\*x/") (CL-TEST::NAME/* "a\\*x/*.*") (CL-TEST::FILE "a\\*x/temp.dat")) (WHEN (PROBE-FILE CL-TEST::NAME) (IF (DIRECTORYP CL-TEST::NAME) (DELETE-DIRECTORY CL-TEST::NAME/) (DELETE-FILE CL-TEST::NAME))) (ENSURE-DIRECTORIES-EXIST CL-TEST::NAME/) (CLOSE (OPEN CL-TEST::FILE :DIRECTION :OUTPUT :IF-EXISTS :ERROR)) (CLOSE (OPEN CL-TEST::FILE :DIRECTION :OUTPUT :IF-EXISTS :SUPERSEDE)) (LENGTH (DIRECTORY "a\\*x/*.*")))
Expected value: 1
Actual value: #<FILE-ERROR #x21044E0B8D>.

(copied and trunated from https://github.com/Clozure/ccl/issues/425#issuecomment-1376247378)

**Comment by kyanha** [comment]
This attempts to use '*' as a literal character in a directory name or file name. Windows does not support this. This test should be completely bypassed on Windows.

**Comment by xrme** [comment]
https://github.com/Clozure/ccl-tests/commit/f803673094b439b004f7615e3f4089ec0d2659e9 excludes this test on Windows.

**Comment by kyanha** [comment]
Thank you very much!
