### ISSUE TITLE
cocoa-ide should be broken out into a separate repository

### ISSUE THREAD

**Issue by kyanha** [Clozure/ccl#434]
On Windows, Linux, and every platform other than MacOS, the cocoa-ide source directory simply takes up 5.5 megs of space for no benefit. In my opinion, ccl-tests would be a much better candidate to be in the main ccl repository, but it was broken out into its own. (At least the tests are applicable to every platform, and they should be run whenever a new ccl is built to ensure that any modifications to the driver didn't break anything.)

I propose that the cocoa-ide directory be moved out into its own repository, so that it can be included only in distributions for MacOS.

**Comment by xrme** [comment]
duplicates #16
