### ISSUE TITLE
CCL:ARGLIST interns symbols in the current package

### ISSUE THREAD

**Issue by eugeneia** [Clozure/ccl#44]
From https://trac.clozure.com/ccl/ticket/1260

> SLSIA:

```
Welcome to Clozure Common Lisp Version 1.10-r16304M  (DarwinX8664)!
? (find-symbol "ARGS")
NIL
NIL
? (arglist 'setf)
(&REST ARGS)
:DECLARATION
? (find-symbol "ARGS")
ARGS
:INTERNAL
```

> The problem occurs only when calling CCL::ARGLIST on macros, not functions.

> I know it's not kosher to complain about the behavior of unexported functions, but swank uses this and it causes real problems. For example, trying to (use-package :cl-who) in a swank session fails because the symbol STR gets interned in cl-user during the swank startup process.

First of all I want to note that `ccl:arglist` is indeed external to the `ccl` package, and seems to be the only way to get lambda lists of functions/macros/..., which is a common operation in introspection tools (SLIME, documentation generators, ...). I would argue this to be a popular feature, and hence a problematic bug.

I’ve investigated a bit, and the interning happens because for macros the lambda list is saved as a string (returned by `%arglist-internal`) which is then parsed by `ccl::%arglist` using `read` in the current package.

In a way this is not a bug since its not defined which package should intern the symbols in question.

**Comment by xrme** [comment]
fixed by #47
