### ISSUE TITLE
init file not loaded

### ISSUE THREAD

**Issue by jhcloos** [Clozure/ccl#444]
running 1.12.1 on a gentoo box, i cannot see any indication that it even tries to load ~/.ccl-init.lisp

there is nothing in an strace and the contents do not get executed.

and the only hit for .ccl-init.lisp in the repo is in the file doc/manual/install.ccldoc.

**Comment by xrme** [comment]
Maybe there is some confusion about what the "home:" logical host is?

On my Mac, I see:
```
? (probe-file "home:")
#P"/Users/rme/"
? (probe-file "~/")
#P"/Users/rme/"
```

The special variable `*ccl-init-file*` contains the name of the init file.

```
(defvar *ccl-init-file*
  #+unix '("home:ccl-init" "home:\\.ccl-init")
  #+windows "home:ccl-init"
  "Global default init file for CCL. This file will be loaded by the first listener process.
   It's probably a better idea to specialize application-init-file than to override this value.")
```

**Comment by edoneel** [comment]
Hi,

So where in the source is the logical host home: defined?

I looked and nothing looked like the right place.

And is there is some way of listing all the logical hosts that are
defined?

Thanks.

cheers

bruce

**Comment by xrme** [comment]
> So where in the source is the logical host home: defined?

https://github.com/Clozure/ccl/blob/master/level-1/l1-pathnames.lisp#L659

I don't think there's a standard way to list them.

**Comment by edoneel** [comment]
Thanks!

**Comment by xrme** [comment]
@jhcloos, I hope you solved your issue.

I think it's probably something to do with your local environment, but please reopen if you want a hand troubleshooting.
