### ISSUE TITLE
MAPCAN/MAPCON Edge cases

### ISSUE THREAD

**Issue by Gleefre** [Clozure/ccl#445]
MAPCAN/MAPCON functions have two edge cases which are not correctly handled in ccl.

```lisp
(mapcan #'identity '(1 2 3))  ; should error, returns 3 instead
(mapcon #'car '(1 2 3))       ; same

(setf *print-circle* t)

;; This returns #1=(1 2 . #1#), which is correct
(let ((lst (list 1 2)))
  (flet ((f (x)
           (declare (ignore x))
           lst))
    (apply #'nconc (mapcar #'f '(1 2)))))

;; Should be equivalent to the previous example, but hangs instead.
(let ((lst (list 1 2)))
  (flet ((f (x)
           (declare (ignore x))
           lst))
    (mapcan #'f '(1 2))))
```

Also please see https://gitlab.common-lisp.net/ansi-test/ansi-test/-/issues/39 .

Tested on ccl v1.12.1 (latest release)

**Comment by xrme** [comment]
There's extensive discussion of this at https://gitlab.common-lisp.net/cmucl/cmucl/-/issues/196

**Comment by xrme** [comment]
@gzacharias maybe you'd be interested in looking at this?

CCL and CMUCL share similar source code for mapcan and friends, but there are a few CCL alterations that look like they were authored by you.
