### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by asmaloney** [Clozure/ccl#447]
Any chance of getting a new release put together?

The last release was 2 years ago and there have been several changes/fixes since then.

**Comment by xrme** [comment]
We certainly could use a new release after all this time.

I'm working on putting together a new release, and hope to complete that in the next few days or so.

**Comment by asmaloney** [comment]
Thanks Matthew!

https://github.com/Clozure/ccl/releases/tag/v1.12.2
