### ISSUE TITLE
CCL on an older Mac Mini

### ISSUE THREAD

**Issue by ghost** [Clozure/ccl#460]
Setup:

Mac Mini mid-2011 Server
Lion (10.7.5)
CCL (ccl-1.11-darwinx86, through a short binary search)
Xcode 4.3.1 for Lion, "installed"

Terminal Session:

> clyde:~ mel$ make
> ~bash: make: command not found # knucklehead

> clyde:~ mel$ cd /Users/mel/Desktop/ccl
> clyde:ccl mel$ ./dx86cl64
> [Friendly startup message elided]
> ? 

[Sorry for any typos, the machine is air gapped and I had to hand enter.]

Let's pretend, for sake of argument, that I am a newbie. 

What now?

**Comment by edoneel** [comment]
Hi,

You need to install the command line utilities.

It used to be

xcode-select --install

most recently on 10.15.

Then make works.

The rest of the instructions are here:

Release Clozure CL 1.12.2 · Clozure/ccl (github.com)
[https://github.com/Clozure/ccl/releases/tag/v1.12.2]

The default build builds for 10.9 and later.  If this won't run on
10.7 I looks as if I can build a 10.7 one for you.

cheers

bruce

**Comment by edoneel** [comment]
Hi,

Does xcode-select --help return anything useful?

cheers

bruce

**Comment by edoneel** [comment]
Hi,

If this old stack exchange posting is to be believed then it seems
that xcode-select no longer has the package available to download

https://stackoverflow.com/questions/9329243/how-to-install-xcode-command-line-tools

It implies that you can download the package from developer.apple.com
using your free Apple Developer account, but, my fading memory is that
the free Developer accounts have gone away.

So give it as shot but you might have to either get a newer MacOS
version (and then a newer intel mac, sorry) or you might have to go
for some version of free tools.

Sorry...

cheers

bruce

**Comment by gmpalter** [comment]
Here’s the link to the OS X Lion command line tools.

https://download.developer.apple.com/Developer_Tools/command_line_tools_os_x_lion_for_xcode__july_2012/Command_Line_Tools_OS_X_Lion_for_Xcode__July_2012.dmg

You'll have to login to a developer account to download it.

  - Gary

P.S., You’re a newbie. Cut my teeth on an IBM 1130 in Summer 1968.

**Comment by xrme** [comment]
It appears that the reporter deleted his GitHub account.
