### ISSUE TITLE
open recent menu

### ISSUE THREAD

**Issue by markklein** [Clozure/ccl#465]
MacOS Sonoma 14.1.1 (23B81)
Clozure Version 1.12-2 (1.12.2)

open recent menu items are whited-out and give me the error "The document “(null)” could not be opened. The file doesn’t exist." when I click on them.

![Screenshot 2023-11-26 at 10 34 01 PM](https://github.com/Clozure/ccl/assets/8991514/2169ea17-21ee-45df-9203-c4ee2f397e48)

**Comment by xrme** [comment]
duplicate of #513
