### ISSUE TITLE
Socket reading seems to be really slow (or backed up)

### ISSUE THREAD

**Issue by SuperDisk** [Clozure/ccl#506]
I know this is a pretty poor bug report, but I'm doing a game in CL, and CCL seems to exhibit a problem with reading from TCP sockets. In the video, 4 instances of the game are running. The top left is CCL, bottom right is ECL, and the other two are SBCL.

In the other implementations, all network messages are processed in essentially realtime-- when any player jumps, they are all synchronized. In CCL however, there is a massive delay between when the event actually happens and when CCL processes it. This only came to light now since up until now the game's network traffic had been pretty light, but I added some stuff which makes it much more chatty-- as a result, it seems like CCL can't "keep up" with the level of messages coming in and lags. It can send messages fine though (note that whatever it sends is immediately processed by the other clients).

I'm using `websocket-driver` which basically just spawns a thread and calls `read-websocket-frame` directly on a CCL socket stream in a very simple loop:

https://github.com/fukamachi/websocket-driver/blob/17ba5535fb1c4fe43e7e8ac786e8b61a174fcba3/src/ws/client.lisp#L188

`read-websocket-frame` is here and doesn't look like it's doing anything fancy:

https://github.com/fukamachi/websocket-driver/blob/17ba5535fb1c4fe43e7e8ac786e8b61a174fcba3/src/ws/base.lisp#L202

https://github.com/Clozure/ccl/assets/1688837/63315546-b6c6-4a37-a2c4-510d6a109dd5

Any idea why this differs so much from the other implementations?

**Comment by xrme** [comment]
Here's a wild guess: is the server socket created with `:nodelay t`? I see from the usocket sources that some backends turn on nodelay on by default, but that's not the default in the CCL backend.

(For background, see, for example, https://eklitzke.org/the-caveats-of-tcp-nodelay).

**Comment by SuperDisk** [comment]
I don't believe so. `usocket` doesn't specify it unless you pass it as a keyword argument, and `websocket-driver` doesn't specify it.

**Comment by xrme** [comment]
I was trying to say that in your situation (latency-sensitive messages) it is important to use `:nodelay t`.

The usocket backend for enables nodelay by default on SBCL and ECL. The usocket backend for CCL does not enable it by default, so you would have to pass `:nodelay t` explicitly (or change usocket).

**Comment by binghe** [comment]
> I was trying to say that in your situation (latency-sensitive messages) it is important to use `:nodelay t`.
> 
> The usocket backend for SBCL and ECL enables nodelay by default. The usocket backend for CCL does not enable it by default, so you would have to pass `:nodelay t` explicitly (or change usocket).

Thanks for pointing out this issue (of usocket). I think it makes sense to change the CCL backend's default value of `nodelay` to T, to be consistent with other backends.

**Comment by xrme** [comment]
@SuperDisk I'm glad you tried CCL and reported these problems. Did you get a chance to see if `:nodelay t` helps you?

I see that usocket has been changed so that `:nodelay t` is the default on CCL too: https://github.com/usocket/usocket/commit/cb7ab3dc3fafe78b8abe5816d3284d48907e5752

 so maybe that will make things easier for you if `:nodelay t` ends up being the solution:

**Comment by SuperDisk** [comment]
Ah I'm sorry I didn't get back to this quickly. When I tried `:nodelay`, I noticed that movement was indeed smooth so I thought that must be the culprit, then I reverted it and noticed that it was working like that as well-- so now I can't reproduce it. If it happens again I'll try to figure out what causes it...
