### ISSUE TITLE
Error(s) during kernel compilation in linux ubuntu

### ISSUE THREAD

**Issue by raranibar** [Clozure/ccl#509]
Hi,
I've tried to install ccl in:
Linux srvbdpostgresql 5.15.0-116-generic #126-Ubuntu SMP Mon Jul 1 10:14:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

I followed the instructions:
git clone https://github.com/Clozure/ccl.git
curl -L -O https://github.com/Clozure/ccl/releases/latest/download/linuxx86.tar.gz
cd ccl
tar xf ../linuxx86.tar.gz
./lx86cl64 -n

bun when i ran the last instruction (./lx86cl64 -n) I get this error: **;Wrote bootstrapping image: #P"/home/srvbdpostgresql/ccl/x86-boot64"
;Building lisp-kernel ...
> Error: Error(s) during kernel compilation.
>        make: Entering directory '/home/srvbdpostgresql/ccl/lisp-kernel/linuxx8664'**

How can i resolve this problem?

[lx86cl64.txt](https://github.com/user-attachments/files/16351723/lx86cl64.txt)

**Comment by gmpalter** [comment]
You need to install m4. 

```
sudo apt install m4
```

**Comment by raranibar** [comment]
thank you

**Comment by xrme** [comment]
I assume that you're able to build now, so I'll close the issue.
