### ISSUE TITLE
maybe support package local nicknames

### ISSUE THREAD

**Issue by xrme** [Clozure/ccl#67]
Several users have expressed interest in package-local nicknames.

There's a mailing list thread about it at https://lists.clozure.com/pipermail/openmcl-devel/2013-February/thread.html

**Comment by budden** [comment]
Hi! In my budden-tools there is an implementation of package-local nicknames, based on a modified reader. Few days ago I added CCL support. https://bitbucket.org/budden/budden-tools

**Comment by phoe** [comment]
Fixed by #111
