### ISSUE TITLE
Should I report bugs here or where the docs tell me to?

### ISSUE THREAD

**Issue by Devon7** [Clozure/ccl#68]
https://ccl.clozure.com
Clozure Common Lisp	Download	Wiki	Report Bug http://trac.clozure.com/ccl/newticket
...
Reporting bugs
To report a bug or request a feature, please create a ticket http://trac.clozure.com/ccl/newticket

**Comment by xrme** [comment]
Here, preferably.

I updated the "report a bug" links on http://ccl.clozure.com to point here.  I also put a notice on http://trac.clozure.com/ccl that refers users here.

Thanks.
