### ISSUE TITLE
./lx86cl: No such file or directory on 64bit ubuntu

### ISSUE THREAD

**Issue by PineappleJelly** [Clozure/ccl#69]
I am running ccl on an Ubuntu 64 VM and I am having trouble getting lx86cl to run. This is a clean install of ubuntu with nothing installed on it but what comes with it by default, build-essential and subversion. I do not think the fact that I'm working on a virtual machine is causing the issue.

I followed the instructions to install ccl from https://ccl.clozure.com/install.html and the associated webpages. 
I used the command `svn co http://svn.clozure.com/publicsvn/openmcl/release/1.11/linuxx86/ccl`
and this created the directory in `/home/username/ccl`.

I attempted to run ccl directly from the terminal using the command: `./lx86cl64` and this started the 64 bit ccl just fine.
However using the command `./lx86cl` returned `bash: ./lx86cl: No such file or directory` (same goes for trying to set up the `ccl` script in  `/usr/local/bin` . ccl64 works fine, but not ccl).
Which is strange because when I move to the ~/ccl directory the lx86cl binary is included in the folder.

What I haven't done:
- Attempted to try this on a 32 bit version of unbuntu
- Compiled from the source

In the past I just shrugged and moved on using ccl64 only, but now I am at a point where I need to test to make sure my project works in the 32bit version. So, I'm trying to make sure each works before I set up emacs, slime and quicklisp on this clean VM.

Any thoughts on getting the 32 bit version of CCL to work for this setup? Is this a true bug? Am I alone out here with this issue? I will reply with my experiments in other VMs later.

I'm not very experienced with linux so please let me know if I'm missing something obvious!

**Comment by binghe** [comment]
I see 3 possible reasons:

1. Your 64-bit Ubuntu environment doesn't have 32-bit compatible libraries (GLIBC and others) packages installed.
2. The "lx86cl" file simply has no executable flag (+x).
3. The GLIBC version is too old in your Ubuntu environment, in this case you need to rebuild CCL kernel by executing `make` in `~/ccl/lisp-kernel/linuxx8632` directory and try again.

**Comment by xrme** [comment]
You need to install 32-bit libraries.

I just tried it on a fresh install of Ubuntu 16.04, and this worked for me:
```
# dpkg --add-architecture i386
# apt update
# apt install libc-dev:i386
```

**Comment by PineappleJelly** [comment]
It looks like the issue was the first of those 3 reasons, I didn't have the 32 bit libraries installed. Those commands did the trick!

Thanks guys! I wasn't sure where to turn with my problem and it apparently was a pretty simple solution.
