### ISSUE TITLE
Compiler error: The value NIL is not of the expected type SIMPLE-VECTOR.

### ISSUE THREAD

**Issue by pfdietz** [Clozure/ccl#74]
(defun f1 (c)
  (block b1
    (if (and c nil)
        (return-from b1
          (ash (values 0 (list 1))
               (min 87 (case 0 (t c)))))
        0)))

==>

The value NIL is not of the expected type SIMPLE-VECTOR.
   [Condition of type TYPE-ERROR]
[...]
Backtrace:
  0: (CCL::FREE-VARPARTS-VECTOR NIL)
  1: (CCL::ELIDE-VINSN #<NIL>)
  2: (CCL::ELIMINATE-DEAD-CODE #<DLL-HEADER #x302000B1341D>)
  3: (CCL::OPTIMIZE-VINSNS #<DLL-HEADER #x302000B1341D>)
  4: (CCL::X862-COMPILE #<CCL::AFUNC #x302000B155DD> NIL T)

Found in the current release of ccl (1.11-r16635) for x86-64 under Linux.

This was found with the random tester, which generates random lisp functions and attempts to find problems with them.  It often finds bugs in dead code elimination in compilers, since the generated functions have a lot of dead code.

**Comment by xrme** [comment]
I think this can be solved by not freelisting vinsn-varparts, as in dcd8966d57dcb94340abdc2310a8d14e4f528514.  (Note that the 1.12 development branch doesn't have a problem here.)

It is possible that there might be some bootstrapping difficulties.

**Comment by xrme** [comment]
ac9394c breaks the ARM compiler.  Making `arm2-predicate-block` a no-op (as is done in the 1.12 development branch) will work around it.

**Comment by xrme** [comment]
Made `arm2-predicate-block` a no-op in 8ad78a961b765eef8ff55111fa898cab6d7bb63b.

The 1.11.5 release includes this fix.
